// Dados Mock para demonstração do sistema

import type {
  Usuario,
  Instrutor,
  Coordenador,
  Admin,
  Aluno,
  Turma,
  Curso,
  Ementa,
  Interessado,
  DiarioAula,
  AnotacaoAluno,
  AulaCancelada,
  MetricasGerais,
} from './types';

// Usuários Mock
export const mockUsuarios: Usuario[] = [
  {
    id: '1',
    nome: 'Admin Sistema',
    email: 'admin@escola.com',
    role: 'admin',
    status: 'ativo',
    telefone: '(11) 98765-4321',
    dataCadastro: '2024-01-01',
    ultimoAcesso: '2024-11-02',
  },
  {
    id: '2',
    nome: 'Maria Silva',
    email: 'coordenador@escola.com',
    role: 'coordenador',
    status: 'ativo',
    telefone: '(11) 98765-4322',
    dataCadastro: '2024-01-15',
    ultimoAcesso: '2024-11-02',
  },
  {
    id: '3',
    nome: 'João Santos',
    email: 'instrutor@escola.com',
    role: 'instrutor',
    status: 'ativo',
    telefone: '(11) 98765-4323',
    dataCadastro: '2024-02-01',
    ultimoAcesso: '2024-11-01',
  },
];

// Instrutores Mock
export const mockInstrutores: Instrutor[] = [
  {
    id: '3',
    nome: 'João Santos',
    email: 'instrutor@escola.com',
    role: 'instrutor',
    status: 'ativo',
    telefone: '(11) 98765-4323',
    especialidades: ['Programação Web', 'JavaScript', 'React'],
    biografia: 'Desenvolvedor full-stack com 10 anos de experiência.',
    turmasAlocadas: ['1', '2'],
    dataCadastro: '2024-02-01',
    ultimoAcesso: '2024-11-01',
  },
  {
    id: '4',
    nome: 'Ana Paula Oliveira',
    email: 'ana.oliveira@escola.com',
    role: 'instrutor',
    status: 'ativo',
    telefone: '(11) 98765-4324',
    especialidades: ['Design UX/UI', 'Figma', 'Design Thinking'],
    biografia: 'Designer com foco em experiência do usuário.',
    turmasAlocadas: ['3'],
    dataCadastro: '2024-02-15',
    ultimoAcesso: '2024-11-02',
  },
  {
    id: '5',
    nome: 'Carlos Mendes',
    email: 'carlos.mendes@escola.com',
    role: 'instrutor',
    status: 'ativo',
    telefone: '(11) 98765-4325',
    especialidades: ['Python', 'Data Science', 'Machine Learning'],
    biografia: 'Cientista de dados com PhD em IA.',
    turmasAlocadas: ['4'],
    dataCadastro: '2024-03-01',
    ultimoAcesso: '2024-11-01',
  },
];

// Cursos Mock
export const mockCursos: Curso[] = [
  {
    id: '1',
    nome: 'Desenvolvimento Web Full Stack',
    descricao: 'Aprenda a desenvolver aplicações web completas.',
    cargaHoraria: 120,
    nivelEnsino: 'Intermediário',
    objetivos: [
      'Dominar HTML, CSS e JavaScript',
      'Criar aplicações com React',
      'Desenvolver APIs com Node.js',
    ],
    ativo: true,
  },
  {
    id: '2',
    nome: 'Design UX/UI',
    descricao: 'Crie interfaces intuitivas e atraentes.',
    cargaHoraria: 80,
    nivelEnsino: 'Básico',
    objetivos: [
      'Entender princípios de UX',
      'Dominar ferramentas de design',
      'Criar protótipos interativos',
    ],
    ativo: true,
  },
  {
    id: '3',
    nome: 'Python para Data Science',
    descricao: 'Análise de dados com Python.',
    cargaHoraria: 100,
    nivelEnsino: 'Intermediário',
    objetivos: [
      'Manipular dados com Pandas',
      'Visualizar dados com Matplotlib',
      'Aplicar algoritmos de ML',
    ],
    ativo: true,
  },
];

// Ementas Mock
export const mockEmentas: Ementa[] = [
  {
    id: '1',
    cursoId: '1',
    curso: 'Desenvolvimento Web Full Stack',
    titulo: 'Ementa Desenvolvimento Web - Turno Noite',
    descricao: 'Ementa completa para formação de desenvolvedores full stack com foco em tecnologias modernas.',
    cargaHorariaTotal: 120,
    objetivosGerais: [
      'Capacitar o aluno a desenvolver aplicações web completas',
      'Dominar HTML, CSS, JavaScript e frameworks modernos',
      'Compreender arquitetura de aplicações web',
      'Desenvolver APIs RESTful e integrar com bancos de dados',
    ],
    aulas: [
      {
        id: '1-1',
        numero: 1,
        titulo: 'Introdução ao Desenvolvimento Web',
        tipo: 'teorica',
        cargaHoraria: 3,
        objetivos: [
          'Compreender a arquitetura cliente-servidor',
          'Conhecer as principais tecnologias web',
        ],
        conteudo: [
          'História da web',
          'Como funciona a internet',
          'Cliente vs Servidor',
          'Protocolos HTTP/HTTPS',
        ],
        recursos: ['Slides', 'Vídeos'],
      },
      {
        id: '1-2',
        numero: 2,
        titulo: 'HTML5 - Estrutura e Semântica',
        tipo: 'teorica',
        cargaHoraria: 3,
        objetivos: [
          'Dominar tags HTML5',
          'Criar estruturas semânticas',
        ],
        conteudo: [
          'Tags básicas',
          'Tags semânticas',
          'Formulários',
          'Tabelas',
        ],
        recursos: ['Editor de código', 'Navegador'],
      },
      {
        id: '1-3',
        numero: 3,
        titulo: 'CSS3 - Estilização e Layout',
        tipo: 'pratica',
        cargaHoraria: 4,
        objetivos: [
          'Aplicar estilos CSS',
          'Criar layouts responsivos',
        ],
        conteudo: [
          'Seletores CSS',
          'Box model',
          'Flexbox',
          'Grid',
          'Responsividade',
        ],
        atividadesPraticas: [
          'Criar página responsiva',
          'Exercícios de Flexbox',
        ],
        recursos: ['Editor de código', 'DevTools'],
      },
      {
        id: '1-4',
        numero: 4,
        titulo: 'JavaScript Fundamentos',
        tipo: 'teorica',
        cargaHoraria: 4,
        objetivos: [
          'Compreender sintaxe JavaScript',
          'Manipular DOM',
        ],
        conteudo: [
          'Variáveis e tipos',
          'Estruturas de controle',
          'Funções',
          'Manipulação do DOM',
        ],
        recursos: ['Editor de código', 'Console do navegador'],
      },
      {
        id: '1-5',
        numero: 5,
        titulo: 'Avaliação Módulo Front-end',
        tipo: 'avaliacao',
        cargaHoraria: 3,
        objetivos: [
          'Avaliar conhecimentos adquiridos',
        ],
        conteudo: [
          'Prova teórica',
          'Exercício prático',
        ],
      },
    ],
    materialDidatico: [
      'Apostila Digital Desenvolvimento Web',
      'Livro: Eloquent JavaScript',
      'Acesso à plataforma de exercícios',
    ],
    avaliacoes: [
      {
        id: 'av1-1',
        titulo: 'Avaliação Front-end',
        tipo: 'prova',
        peso: 30,
        criterios: ['Domínio de HTML', 'Domínio de CSS', 'Lógica JavaScript'],
      },
      {
        id: 'av1-2',
        titulo: 'Projeto Final',
        tipo: 'projeto',
        peso: 50,
        criterios: ['Funcionalidade', 'Código limpo', 'Responsividade', 'Criatividade'],
      },
      {
        id: 'av1-3',
        titulo: 'Participação',
        tipo: 'participacao',
        peso: 20,
        criterios: ['Presença', 'Engajamento', 'Exercícios'],
      },
    ],
    ativo: true,
    dataCriacao: '2024-01-15',
    dataAtualizacao: '2024-02-01',
  },
  {
    id: '2',
    cursoId: '2',
    curso: 'Design UX/UI',
    titulo: 'Ementa Design UX/UI - Completo',
    descricao: 'Formação completa em design de experiência do usuário e interfaces.',
    cargaHorariaTotal: 80,
    objetivosGerais: [
      'Compreender princípios de UX',
      'Dominar ferramentas de design',
      'Criar protótipos interativos',
      'Realizar pesquisas com usuários',
    ],
    aulas: [
      {
        id: '2-1',
        numero: 1,
        titulo: 'Introdução ao UX Design',
        tipo: 'teorica',
        cargaHoraria: 3,
        objetivos: [
          'Entender o que é UX',
          'Conhecer a importância do design centrado no usuário',
        ],
        conteudo: [
          'Conceitos de UX',
          'Diferença entre UX e UI',
          'Processo de design',
        ],
        recursos: ['Slides', 'Casos de estudo'],
      },
      {
        id: '2-2',
        numero: 2,
        titulo: 'Pesquisa com Usuários',
        tipo: 'pratica',
        cargaHoraria: 4,
        objetivos: [
          'Realizar entrevistas',
          'Criar personas',
        ],
        conteudo: [
          'Métodos de pesquisa',
          'Entrevistas',
          'Personas',
          'Jornada do usuário',
        ],
        atividadesPraticas: [
          'Criar persona',
          'Mapear jornada do usuário',
        ],
        recursos: ['Templates', 'Ferramentas de mapeamento'],
      },
      {
        id: '2-3',
        numero: 3,
        titulo: 'Prototipagem no Figma',
        tipo: 'pratica',
        cargaHoraria: 5,
        objetivos: [
          'Dominar Figma',
          'Criar protótipos interativos',
        ],
        conteudo: [
          'Interface do Figma',
          'Componentes',
          'Auto layout',
          'Protótipos interativos',
        ],
        atividadesPraticas: [
          'Criar wireframe',
          'Desenvolver protótipo',
        ],
        recursos: ['Figma', 'Bibliotecas de componentes'],
      },
    ],
    materialDidatico: [
      'Guia Completo de UX Design',
      'Acesso ao Figma Pro',
      'Biblioteca de recursos de design',
    ],
    avaliacoes: [
      {
        id: 'av2-1',
        titulo: 'Projeto de Pesquisa',
        tipo: 'trabalho',
        peso: 30,
        criterios: ['Qualidade da pesquisa', 'Personas bem definidas'],
      },
      {
        id: 'av2-2',
        titulo: 'Protótipo Final',
        tipo: 'projeto',
        peso: 50,
        criterios: ['Usabilidade', 'Estética', 'Interatividade'],
      },
      {
        id: 'av2-3',
        titulo: 'Apresentação',
        tipo: 'apresentacao',
        peso: 20,
        criterios: ['Clareza', 'Argumentação', 'Apresentação visual'],
      },
    ],
    ativo: true,
    dataCriacao: '2024-02-01',
  },
  {
    id: '3',
    cursoId: '3',
    curso: 'Python para Data Science',
    titulo: 'Ementa Python Data Science - Intensivo',
    descricao: 'Curso intensivo de análise de dados com Python.',
    cargaHorariaTotal: 100,
    objetivosGerais: [
      'Dominar Python para análise de dados',
      'Utilizar bibliotecas de Data Science',
      'Criar visualizações de dados',
      'Aplicar algoritmos de Machine Learning',
    ],
    aulas: [
      {
        id: '3-1',
        numero: 1,
        titulo: 'Python Básico',
        tipo: 'teorica',
        cargaHoraria: 4,
        objetivos: [
          'Aprender sintaxe Python',
          'Trabalhar com estruturas de dados',
        ],
        conteudo: [
          'Variáveis e tipos',
          'Listas, tuplas, dicionários',
          'Loops e condicionais',
          'Funções',
        ],
        recursos: ['Jupyter Notebook', 'Python 3.x'],
      },
      {
        id: '3-2',
        numero: 2,
        titulo: 'Pandas - Manipulação de Dados',
        tipo: 'pratica',
        cargaHoraria: 5,
        objetivos: [
          'Manipular DataFrames',
          'Limpar e transformar dados',
        ],
        conteudo: [
          'DataFrames e Series',
          'Leitura de arquivos',
          'Limpeza de dados',
          'Agregações',
        ],
        atividadesPraticas: [
          'Análise de dataset real',
          'Limpeza de dados sujos',
        ],
        recursos: ['Jupyter Notebook', 'Datasets'],
      },
      {
        id: '3-3',
        numero: 3,
        titulo: 'Visualização de Dados',
        tipo: 'pratica',
        cargaHoraria: 4,
        objetivos: [
          'Criar gráficos informativos',
          'Comunicar insights',
        ],
        conteudo: [
          'Matplotlib básico',
          'Seaborn',
          'Tipos de gráficos',
          'Storytelling com dados',
        ],
        atividadesPraticas: [
          'Dashboard de visualizações',
        ],
        recursos: ['Jupyter Notebook', 'Bibliotecas de visualização'],
      },
    ],
    materialDidatico: [
      'Python for Data Analysis - Wes McKinney',
      'Notebooks de exemplos',
      'Datasets para prática',
    ],
    avaliacoes: [
      {
        id: 'av3-1',
        titulo: 'Análise Exploratória',
        tipo: 'trabalho',
        peso: 30,
      },
      {
        id: 'av3-2',
        titulo: 'Projeto de Machine Learning',
        tipo: 'projeto',
        peso: 50,
      },
      {
        id: 'av3-3',
        titulo: 'Apresentação de Resultados',
        tipo: 'apresentacao',
        peso: 20,
      },
    ],
    prerequisitos: 'Conhecimentos básicos de programação',
    ativo: true,
    dataCriacao: '2024-03-01',
  },
];

// Turmas Mock
export const mockTurmas: Turma[] = [
  {
    id: '1',
    codigo: 'WEB-2024-01',
    ementaId: '1',
    ementa: 'Ementa Desenvolvimento Web - Turno Noite',
    instrutorId: '3',
    instrutor: 'João Santos',
    status: 'em_andamento',
    dataInicio: '2024-03-01',
    dataFim: '2024-06-30',
    horario: '19:00 - 22:00',
    diasSemana: ['Segunda', 'Quarta'],
    sala: 'Sala 101',
    vagasTotal: 25,
    vagasOcupadas: 22,
    alunos: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22'],
    dataCriacao: '2024-02-01',
  },
  {
    id: '2',
    codigo: 'WEB-2024-02',
    ementaId: '1',
    ementa: 'Ementa Desenvolvimento Web - Turno Noite',
    instrutorId: '3',
    instrutor: 'João Santos',
    status: 'planejada',
    dataInicio: '2024-07-01',
    dataFim: '2024-10-31',
    horario: '14:00 - 17:00',
    diasSemana: ['Terça', 'Quinta'],
    sala: 'Sala 102',
    vagasTotal: 30,
    vagasOcupadas: 15,
    alunos: ['23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
    dataCriacao: '2024-05-15',
  },
  {
    id: '3',
    codigo: 'UX-2024-01',
    ementaId: '2',
    ementa: 'Ementa Design UX/UI - Completo',
    instrutorId: '4',
    instrutor: 'Ana Paula Oliveira',
    status: 'em_andamento',
    dataInicio: '2024-04-01',
    dataFim: '2024-07-15',
    horario: '09:00 - 12:00',
    diasSemana: ['Segunda', 'Quarta', 'Sexta'],
    sala: 'Sala 201',
    vagasTotal: 20,
    vagasOcupadas: 18,
    alunos: ['38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55'],
    dataCriacao: '2024-03-01',
  },
  {
    id: '4',
    codigo: 'PY-2024-01',
    ementaId: '3',
    ementa: 'Ementa Python Data Science - Intensivo',
    instrutorId: '5',
    instrutor: 'Carlos Mendes',
    status: 'em_andamento',
    dataInicio: '2024-05-01',
    dataFim: '2024-08-31',
    horario: '19:00 - 22:00',
    diasSemana: ['Terça', 'Quinta'],
    sala: 'Lab 301',
    vagasTotal: 20,
    vagasOcupadas: 12,
    alunos: ['56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67'],
    dataCriacao: '2024-04-01',
  },
];

// Alunos Mock (amostra)
export const mockAlunos: Aluno[] = [
  {
    id: '1',
    nome: 'Pedro Henrique Costa',
    email: 'pedro.costa@email.com',
    telefone: '(11) 99876-5432',
    cpf: '123.456.789-00',
    dataNascimento: '1998-05-15',
    endereco: {
      rua: 'Rua das Flores',
      numero: '123',
      bairro: 'Capão Redondo',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05860000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-20',
  },
  {
    id: '2',
    nome: 'Juliana Fernandes',
    email: 'juliana.fernandes@email.com',
    telefone: '(11) 99876-5433',
    cpf: '234.567.890-11',
    dataNascimento: '2000-08-22',
    endereco: {
      rua: 'Avenida dos Trabalhadores',
      numero: '456',
      bairro: 'Jardim Ângela',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05833000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-21',
  },
  {
    id: '3',
    nome: 'Lucas Almeida',
    email: 'lucas.almeida@email.com',
    telefone: '(11) 99876-5434',
    cpf: '345.678.901-22',
    dataNascimento: '1999-11-10',
    endereco: {
      rua: 'Rua São João',
      numero: '789',
      bairro: 'Cidade Tiradentes',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '08470000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-22',
  },
  {
    id: '4',
    nome: 'Mariana Santos',
    email: 'mariana.santos@email.com',
    telefone: '(11) 99876-5435',
    cpf: '456.789.012-33',
    dataNascimento: '2001-03-18',
    endereco: {
      rua: 'Rua da Esperança',
      numero: '234',
      bairro: 'Brasilândia',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '02800000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-23',
  },
  {
    id: '5',
    nome: 'Rafael Oliveira',
    email: 'rafael.oliveira@email.com',
    telefone: '(11) 99876-5436',
    cpf: '567.890.123-44',
    dataNascimento: '1997-07-25',
    endereco: {
      rua: 'Avenida Central',
      numero: '567',
      bairro: 'Grajaú',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04850000',
    },
    status: 'concluido',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
  },
  {
    id: '6',
    nome: 'Camila Rodrigues',
    email: 'camila.rodrigues@email.com',
    telefone: '(11) 99876-5437',
    cpf: '678.901.234-55',
    dataNascimento: '2002-01-12',
    endereco: {
      rua: 'Rua das Palmeiras',
      numero: '890',
      bairro: 'Parelheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04890000',
    },
    status: 'ativo',
    turmaId: '2',
    turma: 'WEB-2024-02',
    dataMatricula: '2024-06-15',
  },
  {
    id: '7',
    nome: 'Thiago Souza',
    email: 'thiago.souza@email.com',
    telefone: '(11) 99876-5438',
    cpf: '789.012.345-66',
    dataNascimento: '1999-04-30',
    endereco: {
      rua: 'Rua do Comércio',
      numero: '321',
      bairro: 'São Miguel Paulista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '08010000',
    },
    status: 'ativo',
    turmaId: '2',
    turma: 'WEB-2024-02',
    dataMatricula: '2024-06-16',
  },
  {
    id: '8',
    nome: 'Amanda Silva',
    email: 'amanda.silva@email.com',
    telefone: '(11) 99876-5439',
    cpf: '890.123.456-77',
    dataNascimento: '2000-09-18',
    endereco: {
      rua: 'Avenida Principal',
      numero: '654',
      bairro: 'Itaquera',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '08220000',
    },
    status: 'ativo',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-07-10',
  },
  {
    id: '9',
    nome: 'Bruno Costa',
    email: 'bruno.costa@email.com',
    telefone: '(11) 99876-5440',
    cpf: '901.234.567-88',
    dataNascimento: '1998-11-25',
    endereco: {
      rua: 'Rua Nova',
      numero: '987',
      bairro: 'Capão Redondo',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05860100',
    },
    status: 'evadido',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-25',
  },
  {
    id: '10',
    nome: 'Letícia Martins',
    email: 'leticia.martins@email.com',
    telefone: '(11) 99876-5441',
    cpf: '012.345.678-99',
    dataNascimento: '2001-06-14',
    endereco: {
      rua: 'Rua das Acácias',
      numero: '147',
      bairro: 'Jardim São Luís',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05813000',
    },
    status: 'concluido',
    turmaId: '2',
    turma: 'WEB-2024-02',
    dataMatricula: '2024-06-17',
  },
  {
    id: '11',
    nome: 'Gabriel Santos',
    email: 'gabriel.santos@email.com',
    telefone: '(11) 99876-5442',
    cpf: '123.456.789-10',
    dataNascimento: '1997-03-22',
    endereco: {
      rua: 'Rua do Progresso',
      numero: '258',
      bairro: 'Jardim Ângela',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05833100',
    },
    status: 'ativo',
    turmaId: '4',
    turma: 'DATA-2024-01',
    dataMatricula: '2024-08-05',
  },
  {
    id: '12',
    nome: 'Patrícia Lima',
    email: 'patricia.lima@email.com',
    telefone: '(11) 99876-5443',
    cpf: '234.567.890-21',
    dataNascimento: '2002-07-08',
    endereco: {
      rua: 'Avenida das Nações',
      numero: '369',
      bairro: 'Cidade Tiradentes',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '08470100',
    },
    status: 'ativo',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-07-11',
  },
];

// Interessados Mock
export const mockInteressados: Interessado[] = [
  // Voluntários
  {
    id: '1',
    tipo: 'voluntario',
    nome: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    telefone: '(11) 99999-1111',
    idade: 28,
    dataNascimento: '1996-03-15',
    genero: 'feminino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Tecnologia',
    endereco: {
      rua: 'Rua dos Voluntários',
      numero: '100',
      bairro: 'Vila Mariana',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04015000',
    },
    motivoVoluntariado: 'Quero contribuir com meus conhecimentos em tecnologia para ajudar pessoas a aprenderem programação e terem melhores oportunidades no mercado de trabalho.',
    habilidadesExperiencia: 'Desenvolvedora Full Stack com 5 anos de experiência em React, Node.js e banco de dados. Experiência em mentoria de desenvolvedores júnior.',
    nivelDisponibilidade: '8 horas por semana',
    experienciaVoluntariado: true,
    detalhesExperienciaVoluntariado: 'Fui voluntária em uma ONG de ensino de programação para jovens de baixa renda por 1 ano. Foi uma experiência muito gratificante ver o progresso dos alunos.',
    corRaca: 'parda',
    deficienciaFisica: false,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    status: 'novo',
    dataRegistro: '2024-10-28',
    origem: 'Instagram',
  },
  {
    id: '2',
    tipo: 'voluntario',
    nome: 'Ricardo Souza',
    email: 'ricardo.souza@email.com',
    telefone: '(11) 99999-2222',
    idade: 35,
    dataNascimento: '1989-07-22',
    genero: 'masculino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Educação',
    endereco: {
      rua: 'Avenida Brigadeiro Faria Lima',
      numero: '2000',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01452000',
    },
    motivoVoluntariado: 'Sempre acreditei no poder da educação para transformar vidas. Quero usar minha experiência como professor para ajudar mais pessoas.',
    habilidadesExperiencia: 'Professor de matemática com 10 anos de experiência. Especialista em metodologias ativas e educação inclusiva.',
    nivelDisponibilidade: 'Mais de 10 horas por semana',
    experienciaVoluntariado: true,
    detalhesExperienciaVoluntariado: 'Participei de projetos de reforço escolar em comunidades carentes e também dei aulas em prisões.',
    corRaca: 'branca',
    deficienciaFisica: false,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    status: 'contatado',
    dataRegistro: '2024-10-25',
    dataContato: '2024-10-26',
    origem: 'Google',
  },
  {
    id: '3',
    tipo: 'voluntario',
    nome: 'Camila Rodrigues',
    email: 'camila.rodrigues@email.com',
    telefone: '(11) 99999-3333',
    idade: 24,
    dataNascimento: '2000-11-08',
    genero: 'feminino',
    escolaridade: 'superior_incompleto',
    cursoInteresse: 'Design',
    endereco: {
      rua: 'Rua Augusta',
      numero: '500',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01305000',
    },
    motivoVoluntariado: 'Como designer, quero usar minhas habilidades para ajudar organizações sociais a terem uma comunicação visual mais efetiva e impactante.',
    habilidadesExperiencia: 'Designer UX/UI com experiência em Figma, Adobe XD e ferramentas de prototipagem. Conhecimentos em design thinking e acessibilidade.',
    nivelDisponibilidade: '6 horas por semana',
    experienciaVoluntariado: false,
    corRaca: 'preta',
    deficienciaFisica: false,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    status: 'matriculado',
    dataRegistro: '2024-10-30',
    dataContato: '2024-11-01',
    origem: 'Indicação',
  },
  {
    id: '11',
    tipo: 'voluntario',
    nome: 'Paulo Henrique Costa',
    email: 'paulo.costa@email.com',
    telefone: '(11) 98888-4444',
    idade: 42,
    dataNascimento: '1982-05-18',
    genero: 'masculino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Administração',
    endereco: {
      rua: 'Rua Vergueiro',
      numero: '1500',
      bairro: 'Liberdade',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01504000',
    },
    motivoVoluntariado: 'Tenho experiência em gestão empresarial e quero ajudar ONGs a se organizarem melhor e alcançarem seus objetivos de forma mais eficiente.',
    habilidadesExperiencia: 'Administrador com MBA em Gestão de Projetos. 15 anos de experiência em gestão empresarial, planejamento estratégico e captação de recursos.',
    nivelDisponibilidade: '4 horas por semana',
    experienciaVoluntariado: true,
    detalhesExperienciaVoluntariado: 'Fui conselheiro fiscal de uma ONG de proteção animal por 3 anos.',
    corRaca: 'branca',
    deficienciaFisica: true,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    especificacaoDeficiencia: 'Uso cadeira de rodas devido a lesão medular',
    status: 'matriculado',
    dataRegistro: '2024-09-15',
    dataContato: '2024-09-16',
    origem: 'LinkedIn',
  },
  {
    id: '12',
    tipo: 'voluntario',
    nome: 'Mariana Santos Oliveira',
    email: 'mariana.santos.o@email.com',
    telefone: '(11) 97777-5555',
    idade: 31,
    dataNascimento: '1993-02-28',
    genero: 'feminino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Marketing',
    endereco: {
      rua: 'Alameda Santos',
      numero: '800',
      bairro: 'Jardins',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01418000',
    },
    motivoVoluntariado: 'Acredito que boas estratégias de marketing podem amplificar o impacto social de organizações que fazem a diferença.',
    habilidadesExperiencia: 'Especialista em marketing digital, mídias sociais e comunicação. Experiência em campanhas de captação de recursos e engajamento.',
    nivelDisponibilidade: '6 horas por semana',
    experienciaVoluntariado: false,
    corRaca: 'indigena',
    etnia: 'Guarani',
    deficienciaFisica: false,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    status: 'contatado',
    dataRegistro: '2024-11-05',
    dataContato: '2024-11-06',
    origem: 'Site',
  },
  // Alunos Interessados
  {
    id: '4',
    tipo: 'aluno',
    nome: 'João Pedro Silva',
    email: 'joao.pedro@email.com',
    telefone: '(11) 98765-4321',
    idade: 17,
    dataNascimento: '2007-05-15',
    cpf: '12345678901',
    genero: 'masculino',
    escolaridade: 'medio_incompleto',
    cursoInteresse: 'Desenvolvimento Web Full Stack',
    endereco: {
      rua: 'Rua das Flores',
      numero: '123',
      complemento: 'Apt 45',
      bairro: 'Centro',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234567',
    },
    responsavel: {
      nome: 'Maria Silva',
      parentesco: 'Mãe',
    },
    contatoEmergencia: {
      nome: 'José Silva',
      telefone: '(11) 98765-1234',
      parentesco: 'Pai',
    },
    corRaca: 'parda',
    alergias: 'Nenhuma',
    deficiencias: 'Nenhuma',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: true,
      outro: false,
    },
    status: 'novo',
    dataRegistro: '2024-11-01',
    origem: 'Site',
  },
  {
    id: '5',
    tipo: 'aluno',
    nome: 'Ana Carolina Oliveira',
    email: 'ana.carolina@email.com',
    telefone: '(11) 97654-3210',
    idade: 22,
    dataNascimento: '2002-08-20',
    cpf: '98765432109',
    genero: 'feminino',
    escolaridade: 'superior_incompleto',
    cursoInteresse: 'Design UX/UI',
    endereco: {
      rua: 'Avenida Paulista',
      numero: '1000',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01310100',
    },
    contatoEmergencia: {
      nome: 'Carla Oliveira',
      telefone: '(11) 97654-9876',
      parentesco: 'Mãe',
    },
    corRaca: 'branca',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: false,
      outro: false,
    },
    status: 'contatado',
    dataRegistro: '2024-10-28',
    dataContato: '2024-10-29',
    origem: 'Instagram',
  },
  {
    id: '6',
    tipo: 'aluno',
    nome: 'Lucas Gabriel Santos',
    email: 'lucas.gabriel@email.com',
    telefone: '(11) 96543-2109',
    idade: 19,
    dataNascimento: '2005-03-10',
    cpf: '45678912345',
    genero: 'masculino',
    escolaridade: 'medio_completo',
    cursoInteresse: 'Python para Data Science',
    endereco: {
      rua: 'Rua da Consolação',
      numero: '456',
      complemento: 'Casa 2',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01302000',
    },
    contatoEmergencia: {
      nome: 'Pedro Santos',
      telefone: '(11) 96543-7890',
      parentesco: 'Irmão',
    },
    corRaca: 'preta',
    alergias: 'Lactose',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: false,
      comprovanteResidencia: true,
      outro: false,
    },
    status: 'novo',
    dataRegistro: '2024-11-02',
    origem: 'Facebook',
  },
  {
    id: '7',
    tipo: 'aluno',
    nome: 'Beatriz Ferreira Costa',
    email: 'beatriz.ferreira@email.com',
    telefone: '(11) 95432-1098',
    idade: 25,
    dataNascimento: '1999-12-05',
    cpf: '78912345678',
    genero: 'feminino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Desenvolvimento Web Full Stack',
    endereco: {
      rua: 'Rua Augusta',
      numero: '789',
      bairro: 'Jardins',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01304000',
    },
    contatoEmergencia: {
      nome: 'Claudia Costa',
      telefone: '(11) 95432-5678',
      parentesco: 'Mãe',
    },
    corRaca: 'branca',
    deficiencias: 'Deficiência visual leve (usa óculos)',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: true,
      outro: true,
    },
    status: 'matriculado',
    dataRegistro: '2024-10-20',
    dataContato: '2024-10-21',
    origem: 'LinkedIn',
  },
  {
    id: '8',
    tipo: 'aluno',
    nome: 'Gabriel Henrique Alves',
    email: 'gabriel.alves@email.com',
    telefone: '(11) 94321-0987',
    idade: 16,
    dataNascimento: '2008-07-22',
    cpf: '32165498732',
    genero: 'masculino',
    escolaridade: 'medio_incompleto',
    cursoInteresse: 'Design UX/UI',
    endereco: {
      rua: 'Rua Oscar Freire',
      numero: '321',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01426000',
    },
    responsavel: {
      nome: 'Roberto Alves',
      parentesco: 'Pai',
    },
    contatoEmergencia: {
      nome: 'Fernanda Alves',
      telefone: '(11) 94321-4567',
      parentesco: 'Mãe',
    },
    corRaca: 'amarela',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: false,
      comprovanteEscolaridade: true,
      comprovanteResidencia: true,
      outro: false,
    },
    status: 'novo',
    dataRegistro: '2024-11-03',
    origem: 'Indicação',
  },
  {
    id: '9',
    tipo: 'aluno',
    nome: 'Juliana Martins Souza',
    email: 'juliana.martins@email.com',
    telefone: '(11) 93210-9876',
    idade: 20,
    dataNascimento: '2004-04-18',
    cpf: '65432178965',
    genero: 'feminino',
    escolaridade: 'superior_incompleto',
    cursoInteresse: 'Python para Data Science',
    endereco: {
      rua: 'Avenida Rebouças',
      numero: '987',
      complemento: 'Bloco B',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05401000',
    },
    contatoEmergencia: {
      nome: 'Ricardo Souza',
      telefone: '(11) 93210-1234',
      parentesco: 'Tio',
    },
    corRaca: 'parda',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: false,
      outro: false,
    },
    status: 'contatado',
    dataRegistro: '2024-10-30',
    dataContato: '2024-10-31',
    origem: 'Google',
  },
  {
    id: '10',
    tipo: 'aluno',
    nome: 'Thiago Araújo Lima',
    email: 'thiago.araujo@email.com',
    telefone: '(11) 92109-8765',
    idade: 23,
    dataNascimento: '2001-09-30',
    cpf: '15975348621',
    genero: 'masculino',
    escolaridade: 'medio_completo',
    cursoInteresse: 'Desenvolvimento Web Full Stack',
    endereco: {
      rua: 'Rua Haddock Lobo',
      numero: '654',
      bairro: 'Cerqueira César',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01414000',
    },
    contatoEmergencia: {
      nome: 'Amanda Lima',
      telefone: '(11) 92109-3456',
      parentesco: 'Irmã',
    },
    corRaca: 'indigena',
    etnia: 'Guarani',
    alergias: 'Amendoim',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: true,
      outro: false,
    },
    status: 'desistente',
    dataRegistro: '2024-10-15',
    dataContato: '2024-10-16',
    origem: 'Site',
  },
];

// Diários de Aula Mock
export const mockDiarios: DiarioAula[] = [
  {
    id: '1',
    turmaId: '1',
    instrutorId: '3',
    data: '2024-03-04',
    numeroAula: 1,
    tipo: 'teorica',
    conteudo: 'Introdução ao HTML5 - Estrutura básica, tags semânticas',
    resumo: 'Apresentação do curso e fundamentos de HTML5.',
    presencas: [
      { alunoId: '1', alunoNome: 'Pedro Henrique Costa', status: 'presente' },
      { alunoId: '2', alunoNome: 'Juliana Fernandes', status: 'presente' },
      { alunoId: '3', alunoNome: 'Lucas Almeida', status: 'ausente' },
    ],
    dataCriacao: '2024-03-04',
  },
];

// Métricas Gerais Mock
export const mockMetricasGerais: MetricasGerais = {
  totalTurmas: 8,
  turmasAtivas: 4,
  totalAlunos: 156,
  alunosAtivos: 142,
  totalInstrutores: 6,
  instrutoresAtivos: 5,
  totalInteressados: 45,
  interessadosNovos: 12,
  taxaConversao: 68.5,
  taxaEvasao: 8.9,
};

// Métricas Qualitativas Mock
export const mockMetricasQualitativas: import('./types').MetricaQualitativa[] = [
  {
    id: 'mq-1',
    alunoId: '1',
    alunoNome: 'Pedro Henrique Costa',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-15',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 4,
    habilidadeProgramacao: 4,
    candidatandoVagas: true,
    tipoOportunidade: 'processo_seletivo',
    interesseCursoTecnico: true,
    interesseGraduacao: true,
    areaInteresse: 'Análise e Desenvolvimento de Sistemas',
  },
  {
    id: 'mq-2',
    alunoId: '2',
    alunoNome: 'Juliana Fernandes',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-15',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 5,
    habilidadeProgramacao: 4,
    candidatandoVagas: true,
    tipoOportunidade: 'freelancer',
    interesseCursoTecnico: false,
    interesseGraduacao: true,
    areaInteresse: 'Engenharia de Software',
  },
  {
    id: 'mq-3',
    alunoId: '3',
    alunoNome: 'Lucas Almeida',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-16',
    satisfacaoCurso: 4,
    segurancaFerramentasDigitais: 3,
    habilidadeProgramacao: 3,
    candidatandoVagas: false,
    tipoOportunidade: 'nenhuma',
    interesseCursoTecnico: true,
    interesseGraduacao: false,
    areaInteresse: 'Técnico em Informática',
  },
  {
    id: 'mq-4',
    alunoId: '4',
    alunoNome: 'Mariana Santos',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-16',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 4,
    habilidadeProgramacao: 5,
    candidatandoVagas: true,
    tipoOportunidade: 'emprego',
    interesseCursoTecnico: true,
    interesseGraduacao: true,
    areaInteresse: 'Ciência da Computação',
  },
  {
    id: 'mq-5',
    alunoId: '5',
    alunoNome: 'Rafael Oliveira',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-17',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 5,
    habilidadeProgramacao: 5,
    candidatandoVagas: true,
    tipoOportunidade: 'emprego',
    interesseCursoTecnico: false,
    interesseGraduacao: true,
    areaInteresse: 'Sistemas de Informação',
  },
  {
    id: 'mq-6',
    alunoId: '6',
    alunoNome: 'Camila Rodrigues',
    turmaId: '2',
    turmaCodigo: 'WEB-2024-02',
    dataResposta: '2024-10-20',
    satisfacaoCurso: 4,
    segurancaFerramentasDigitais: 4,
    habilidadeProgramacao: 3,
    candidatandoVagas: true,
    tipoOportunidade: 'processo_seletivo',
    interesseCursoTecnico: true,
    interesseGraduacao: false,
  },
  {
    id: 'mq-7',
    alunoId: '7',
    alunoNome: 'Thiago Souza',
    turmaId: '2',
    turmaCodigo: 'WEB-2024-02',
    dataResposta: '2024-10-20',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 4,
    habilidadeProgramacao: 4,
    candidatandoVagas: true,
    tipoOportunidade: 'freelancer',
    interesseCursoTecnico: false,
    interesseGraduacao: true,
    areaInteresse: 'Desenvolvimento de Sistemas',
  },
  {
    id: 'mq-8',
    alunoId: '8',
    alunoNome: 'Amanda Silva',
    turmaId: '3',
    turmaCodigo: 'UX-2024-01',
    dataResposta: '2024-10-22',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 5,
    habilidadeProgramacao: 3,
    candidatandoVagas: true,
    tipoOportunidade: 'emprego',
    interesseCursoTecnico: true,
    interesseGraduacao: true,
    areaInteresse: 'Design Digital',
  },
];

// Histórias de Alunos Mock
export const mockHistoriasAlunos: import('./types').HistoriaAluno[] = [
  {
    id: 'hist-1',
    alunoId: '5',
    alunoNome: 'Rafael Oliveira',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    titulo: 'De Entregador a Desenvolvedor: Minha Jornada de Transformação',
    historia: 'Quando comecei o curso, eu trabalhava como entregador de aplicativo e nunca tinha pensado que programação poderia ser para mim. No início, tudo parecia muito difícil e eu quase desisti várias vezes. Mas os instrutores sempre acreditaram em mim e me incentivaram a continuar.\n\nDepois de 3 meses de curso, consegui meu primeiro freelance criando um site para um pequeno comércio do meu bairro. Foi incrível ver algo que EU criei funcionando e ajudando outra pessoa. Isso me motivou ainda mais.\n\nHoje, após concluir o curso, recebi uma proposta para trabalhar como desenvolvedor júnior em uma startup. Minha vida mudou completamente! Agora posso dar uma vida melhor para minha família e tenho um futuro que antes eu nem imaginava ser possível. Esse curso literalmente transformou minha vida.',
    categoria: 'transformacao',
    dataCompartilhamento: '2024-10-28',
    destacada: true,
    aprovada: true,
  },
  {
    id: 'hist-2',
    alunoId: '2',
    alunoNome: 'Juliana Fernandes',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    titulo: 'Primeira Freelancer e Muitos Sonhos pela Frente',
    historia: 'Sou mãe solo de duas crianças e sempre quis trabalhar de casa para estar mais presente na vida delas. Quando descobri o curso de programação, vi uma oportunidade de mudar minha realidade.\n\nO curso foi desafiador, especialmente conciliando com o cuidado das crianças, mas valeu cada esforço. Aprendi não só a programar, mas também a acreditar mais em mim mesma.\n\nAgora estou fazendo trabalhos como freelancer, criando sites e sistemas para pequenos negócios. Consigo trabalhar de casa, definir meus horários e estar presente quando minhas filhas precisam. Além disso, minha renda aumentou significativamente. Sou muito grata por essa oportunidade!',
    categoria: 'superacao',
    dataCompartilhamento: '2024-10-25',
    destacada: true,
    aprovada: true,
  },
  {
    id: 'hist-3',
    alunoId: '4',
    alunoNome: 'Mariana Santos',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    titulo: 'Conquistando Meu Primeiro Emprego na Área de TI',
    historia: 'Sempre tive curiosidade por tecnologia, mas nunca tinha tido a oportunidade de estudar formalmente. Quando me inscrevi no curso, estava desempregada e muito insegura.\n\nDurante o curso, descobri que tinha talento para programação! Os projetos que desenvolvi me deram confiança para me candidatar a vagas. Após enviar meu portfólio para várias empresas, recebi três convites para entrevistas.\n\nHoje estou feliz trabalhando como desenvolvedora júnior em uma empresa de tecnologia. Além do salário justo, tenho plano de saúde e outros benefícios que nunca tinha tido antes. Estou construindo uma carreira sólida e tenho planos de me especializar ainda mais!',
    categoria: 'conquista',
    dataCompartilhamento: '2024-10-26',
    destacada: true,
    aprovada: true,
  },
  {
    id: 'hist-4',
    alunoId: '1',
    alunoNome: 'Pedro Henrique Costa',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    titulo: 'Programação Abriu Portas que Eu Nem Sabia que Existiam',
    historia: 'Eu estava preso em um emprego que não me satisfazia e não via perspectiva de crescimento. Decidi me inscrever no curso de programação por indicação de um amigo, mas confesso que estava cético.\n\nDurante o curso, percebi que programação é muito mais do que escrever código - é resolver problemas, criar soluções e ajudar pessoas. Isso mudou completamente minha visão.\n\nEstou em processo seletivo para três empresas diferentes e já recebi uma proposta. Mais do que isso, descobri uma paixão que não sabia que tinha. Agora acordo animado para estudar e criar projetos. É incrível sentir que finalmente encontrei meu caminho!',
    categoria: 'inspiracao',
    dataCompartilhamento: '2024-10-27',
    destacada: false,
    aprovada: true,
  },
  {
    id: 'hist-5',
    alunoId: '8',
    alunoNome: 'Amanda Silva',
    turmaId: '3',
    turmaCodigo: 'UX-2024-01',
    titulo: 'Do Sonho à Realidade: Minha Carreira em UX Design',
    historia: 'Sempre gostei de desenhar e criar coisas, mas nunca pensei que isso poderia se tornar uma profissão. O curso de UX/UI Design me mostrou que posso unir criatividade com tecnologia.\n\nAprendi a criar interfaces que realmente ajudam as pessoas e isso me realiza profissionalmente. Durante o curso, redesenhei o aplicativo de uma ONG local como projeto final, e isso abriu muitas portas.\n\nRecentemente, comecei a trabalhar em uma agência digital como designer júnior. Ver meus designs saindo do papel e sendo usados por milhares de pessoas é uma sensação indescritível. Agradeço imensamente pela oportunidade que esse curso me deu!',
    categoria: 'conquista',
    dataCompartilhamento: '2024-10-29',
    destacada: false,
    aprovada: true,
  },
  {
    id: 'hist-6',
    alunoId: '7',
    alunoNome: 'Thiago Souza',
    turmaId: '2',
    turmaCodigo: 'WEB-2024-02',
    titulo: 'Superando Desafios e Alcançando Objetivos',
    historia: 'Venho de uma família humilde e sempre precisei trabalhar desde cedo para ajudar em casa. Estudar programação era um sonho que parecia distante demais.\n\nQuando consegui a vaga no curso gratuito, vi uma luz no fim do túnel. Foi difícil conciliar trabalho e estudos, mas cada linha de código que funcionava era uma vitória.\n\nHoje estou fazendo pequenos trabalhos como freelancer e juntando experiência. Meu objetivo é conseguir um emprego fixo na área até o final do ano. Sei que vou conseguir, porque se cheguei até aqui, posso ir ainda mais longe!',
    categoria: 'superacao',
    dataCompartilhamento: '2024-10-30',
    destacada: false,
    aprovada: true,
  },
];
