// Dados Mock para demonstração do sistema

import type {
  Usuario,
  Instrutor,
  Coordenador,
  Admin,
  Aluno,
  Turma,
  Curso,
  Ementa,
  Interessado,
  DiarioAula,
  AnotacaoAluno,
  AulaCancelada,
  MetricasGerais,
} from './types';

// Usuários Mock
export const mockUsuarios: Usuario[] = [
  {
    id: '1',
    nome: 'Admin Sistema',
    email: 'admin@escola.com',
    role: 'admin',
    status: 'ativo',
    telefone: '(11) 98765-4321',
    dataCadastro: '2024-01-01',
    ultimoAcesso: '2024-11-02',
  },
  {
    id: '2',
    nome: 'Maria Silva',
    email: 'coordenador@escola.com',
    role: 'coordenador',
    status: 'ativo',
    telefone: '(11) 98765-4322',
    dataCadastro: '2024-01-15',
    ultimoAcesso: '2024-11-02',
  },
  {
    id: '3',
    nome: 'João Santos',
    email: 'instrutor@escola.com',
    role: 'instrutor',
    status: 'ativo',
    telefone: '(11) 98765-4323',
    especialidades: ['Programação Web', 'JavaScript', 'React'],
    biografia: 'Desenvolvedor full-stack com 10 anos de experiência.',
    turmasAlocadas: ['1', '2'],
    dataCadastro: '2024-02-01',
    ultimoAcesso: '2024-11-01',
  },
];

// Instrutores Mock
export const mockInstrutores: Instrutor[] = [
  {
    id: '3',
    nome: 'João Santos',
    email: 'instrutor@escola.com',
    role: 'instrutor',
    status: 'ativo',
    telefone: '(11) 98765-4323',
    especialidades: ['Programação Web', 'JavaScript', 'React'],
    biografia: 'Desenvolvedor full-stack com 10 anos de experiência.',
    turmasAlocadas: ['1', '2'],
    dataCadastro: '2024-02-01',
    ultimoAcesso: '2024-11-01',
  },
  {
    id: '4',
    nome: 'Ana Paula Oliveira',
    email: 'ana.oliveira@escola.com',
    role: 'instrutor',
    status: 'ativo',
    telefone: '(11) 98765-4324',
    especialidades: ['Design UX/UI', 'Figma', 'Design Thinking'],
    biografia: 'Designer com foco em experiência do usuário.',
    turmasAlocadas: ['3'],
    dataCadastro: '2024-02-15',
    ultimoAcesso: '2024-11-02',
  },
  {
    id: '5',
    nome: 'Carlos Mendes',
    email: 'carlos.mendes@escola.com',
    role: 'instrutor',
    status: 'ativo',
    telefone: '(11) 98765-4325',
    especialidades: ['Python', 'Data Science', 'Machine Learning'],
    biografia: 'Cientista de dados com PhD em IA.',
    turmasAlocadas: ['4'],
    dataCadastro: '2024-03-01',
    ultimoAcesso: '2024-11-01',
  },
];

// Cursos Mock
export const mockCursos: Curso[] = [
  {
    id: '1',
    nome: 'Desenvolvimento Web Full Stack',
    descricao: 'Aprenda a desenvolver aplicações web completas.',
    cargaHoraria: 120,
    nivelEnsino: 'Intermediário',
    objetivos: [
      'Dominar HTML, CSS e JavaScript',
      'Criar aplicações com React',
      'Desenvolver APIs com Node.js',
    ],
    ativo: true,
  },
  {
    id: '2',
    nome: 'Design UX/UI',
    descricao: 'Crie interfaces intuitivas e atraentes.',
    cargaHoraria: 80,
    nivelEnsino: 'Básico',
    objetivos: [
      'Entender princípios de UX',
      'Dominar ferramentas de design',
      'Criar protótipos interativos',
    ],
    ativo: true,
  },
  {
    id: '3',
    nome: 'Python para Data Science',
    descricao: 'Análise de dados com Python.',
    cargaHoraria: 100,
    nivelEnsino: 'Intermediário',
    objetivos: [
      'Manipular dados com Pandas',
      'Visualizar dados com Matplotlib',
      'Aplicar algoritmos de ML',
    ],
    ativo: true,
  },
];

// Ementas Mock
export const mockEmentas: Ementa[] = [
  {
    id: '1',
    cursoId: '1',
    curso: 'Desenvolvimento Web Full Stack',
    titulo: 'Ementa Desenvolvimento Web - Turno Noite',
    descricao: 'Ementa completa para formação de desenvolvedores full stack com foco em tecnologias modernas.',
    cargaHorariaTotal: 120,
    objetivosGerais: [
      'Capacitar o aluno a desenvolver aplicações web completas',
      'Dominar HTML, CSS, JavaScript e frameworks modernos',
      'Compreender arquitetura de aplicações web',
      'Desenvolver APIs RESTful e integrar com bancos de dados',
    ],
    aulas: [
      {
        id: '1-1',
        numero: 1,
        titulo: 'Introdução ao Desenvolvimento Web',
        tipo: 'teorica',
        cargaHoraria: 3,
        objetivos: [
          'Compreender a arquitetura cliente-servidor',
          'Conhecer as principais tecnologias web',
        ],
        conteudo: [
          'História da web',
          'Como funciona a internet',
          'Cliente vs Servidor',
          'Protocolos HTTP/HTTPS',
        ],
        recursos: ['Slides', 'Vídeos'],
      },
      {
        id: '1-2',
        numero: 2,
        titulo: 'HTML5 - Estrutura e Semântica',
        tipo: 'teorica',
        cargaHoraria: 3,
        objetivos: [
          'Dominar tags HTML5',
          'Criar estruturas semânticas',
        ],
        conteudo: [
          'Tags básicas',
          'Tags semânticas',
          'Formulários',
          'Tabelas',
        ],
        recursos: ['Editor de código', 'Navegador'],
      },
      {
        id: '1-3',
        numero: 3,
        titulo: 'CSS3 - Estilização e Layout',
        tipo: 'pratica',
        cargaHoraria: 4,
        objetivos: [
          'Aplicar estilos CSS',
          'Criar layouts responsivos',
        ],
        conteudo: [
          'Seletores CSS',
          'Box model',
          'Flexbox',
          'Grid',
          'Responsividade',
        ],
        atividadesPraticas: [
          'Criar página responsiva',
          'Exercícios de Flexbox',
        ],
        recursos: ['Editor de código', 'DevTools'],
      },
      {
        id: '1-4',
        numero: 4,
        titulo: 'JavaScript Fundamentos',
        tipo: 'teorica',
        cargaHoraria: 4,
        objetivos: [
          'Compreender sintaxe JavaScript',
          'Manipular DOM',
        ],
        conteudo: [
          'Variáveis e tipos',
          'Estruturas de controle',
          'Funções',
          'Manipulação do DOM',
        ],
        recursos: ['Editor de código', 'Console do navegador'],
      },
      {
        id: '1-5',
        numero: 5,
        titulo: 'Avaliação Módulo Front-end',
        tipo: 'avaliacao',
        cargaHoraria: 3,
        objetivos: [
          'Avaliar conhecimentos adquiridos',
        ],
        conteudo: [
          'Prova teórica',
          'Exercício prático',
        ],
      },
    ],
    materialDidatico: [
      'Apostila Digital Desenvolvimento Web',
      'Livro: Eloquent JavaScript',
      'Acesso à plataforma de exercícios',
    ],
    avaliacoes: [
      {
        id: 'av1-1',
        titulo: 'Avaliação Front-end',
        tipo: 'prova',
        peso: 30,
        criterios: ['Domínio de HTML', 'Domínio de CSS', 'Lógica JavaScript'],
      },
      {
        id: 'av1-2',
        titulo: 'Projeto Final',
        tipo: 'projeto',
        peso: 50,
        criterios: ['Funcionalidade', 'Código limpo', 'Responsividade', 'Criatividade'],
      },
      {
        id: 'av1-3',
        titulo: 'Participação',
        tipo: 'participacao',
        peso: 20,
        criterios: ['Presença', 'Engajamento', 'Exercícios'],
      },
    ],
    ativo: true,
    dataCriacao: '2024-01-15',
    dataAtualizacao: '2024-02-01',
  },
  {
    id: '2',
    cursoId: '2',
    curso: 'Design UX/UI',
    titulo: 'Ementa Design UX/UI - Completo',
    descricao: 'Formação completa em design de experiência do usuário e interfaces.',
    cargaHorariaTotal: 80,
    objetivosGerais: [
      'Compreender princípios de UX',
      'Dominar ferramentas de design',
      'Criar protótipos interativos',
      'Realizar pesquisas com usuários',
    ],
    aulas: [
      {
        id: '2-1',
        numero: 1,
        titulo: 'Introdução ao UX Design',
        tipo: 'teorica',
        cargaHoraria: 3,
        objetivos: [
          'Entender o que é UX',
          'Conhecer a importância do design centrado no usuário',
        ],
        conteudo: [
          'Conceitos de UX',
          'Diferença entre UX e UI',
          'Processo de design',
        ],
        recursos: ['Slides', 'Casos de estudo'],
      },
      {
        id: '2-2',
        numero: 2,
        titulo: 'Pesquisa com Usuários',
        tipo: 'pratica',
        cargaHoraria: 4,
        objetivos: [
          'Realizar entrevistas',
          'Criar personas',
        ],
        conteudo: [
          'Métodos de pesquisa',
          'Entrevistas',
          'Personas',
          'Jornada do usuário',
        ],
        atividadesPraticas: [
          'Criar persona',
          'Mapear jornada do usuário',
        ],
        recursos: ['Templates', 'Ferramentas de mapeamento'],
      },
      {
        id: '2-3',
        numero: 3,
        titulo: 'Prototipagem no Figma',
        tipo: 'pratica',
        cargaHoraria: 5,
        objetivos: [
          'Dominar Figma',
          'Criar protótipos interativos',
        ],
        conteudo: [
          'Interface do Figma',
          'Componentes',
          'Auto layout',
          'Protótipos interativos',
        ],
        atividadesPraticas: [
          'Criar wireframe',
          'Desenvolver protótipo',
        ],
        recursos: ['Figma', 'Bibliotecas de componentes'],
      },
    ],
    materialDidatico: [
      'Guia Completo de UX Design',
      'Acesso ao Figma Pro',
      'Biblioteca de recursos de design',
    ],
    avaliacoes: [
      {
        id: 'av2-1',
        titulo: 'Projeto de Pesquisa',
        tipo: 'trabalho',
        peso: 30,
        criterios: ['Qualidade da pesquisa', 'Personas bem definidas'],
      },
      {
        id: 'av2-2',
        titulo: 'Protótipo Final',
        tipo: 'projeto',
        peso: 50,
        criterios: ['Usabilidade', 'Estética', 'Interatividade'],
      },
      {
        id: 'av2-3',
        titulo: 'Apresentação',
        tipo: 'apresentacao',
        peso: 20,
        criterios: ['Clareza', 'Argumentação', 'Apresentação visual'],
      },
    ],
    ativo: true,
    dataCriacao: '2024-02-01',
  },
  {
    id: '3',
    cursoId: '3',
    curso: 'Python para Data Science',
    titulo: 'Ementa Python Data Science - Intensivo',
    descricao: 'Curso intensivo de análise de dados com Python.',
    cargaHorariaTotal: 100,
    objetivosGerais: [
      'Dominar Python para análise de dados',
      'Utilizar bibliotecas de Data Science',
      'Criar visualizações de dados',
      'Aplicar algoritmos de Machine Learning',
    ],
    aulas: [
      {
        id: '3-1',
        numero: 1,
        titulo: 'Python Básico',
        tipo: 'teorica',
        cargaHoraria: 4,
        objetivos: [
          'Aprender sintaxe Python',
          'Trabalhar com estruturas de dados',
        ],
        conteudo: [
          'Variáveis e tipos',
          'Listas, tuplas, dicionários',
          'Loops e condicionais',
          'Funções',
        ],
        recursos: ['Jupyter Notebook', 'Python 3.x'],
      },
      {
        id: '3-2',
        numero: 2,
        titulo: 'Pandas - Manipulação de Dados',
        tipo: 'pratica',
        cargaHoraria: 5,
        objetivos: [
          'Manipular DataFrames',
          'Limpar e transformar dados',
        ],
        conteudo: [
          'DataFrames e Series',
          'Leitura de arquivos',
          'Limpeza de dados',
          'Agregações',
        ],
        atividadesPraticas: [
          'Análise de dataset real',
          'Limpeza de dados sujos',
        ],
        recursos: ['Jupyter Notebook', 'Datasets'],
      },
      {
        id: '3-3',
        numero: 3,
        titulo: 'Visualização de Dados',
        tipo: 'pratica',
        cargaHoraria: 4,
        objetivos: [
          'Criar gráficos informativos',
          'Comunicar insights',
        ],
        conteudo: [
          'Matplotlib básico',
          'Seaborn',
          'Tipos de gráficos',
          'Storytelling com dados',
        ],
        atividadesPraticas: [
          'Dashboard de visualizações',
        ],
        recursos: ['Jupyter Notebook', 'Bibliotecas de visualização'],
      },
    ],
    materialDidatico: [
      'Python for Data Analysis - Wes McKinney',
      'Notebooks de exemplos',
      'Datasets para prática',
    ],
    avaliacoes: [
      {
        id: 'av3-1',
        titulo: 'Análise Exploratória',
        tipo: 'trabalho',
        peso: 30,
      },
      {
        id: 'av3-2',
        titulo: 'Projeto de Machine Learning',
        tipo: 'projeto',
        peso: 50,
      },
      {
        id: 'av3-3',
        titulo: 'Apresentação de Resultados',
        tipo: 'apresentacao',
        peso: 20,
      },
    ],
    prerequisitos: 'Conhecimentos básicos de programação',
    ativo: true,
    dataCriacao: '2024-03-01',
  },
];

// Turmas Mock
export const mockTurmas: Turma[] = [
  {
    id: '1',
    codigo: 'WEB-2024-01',
    ementaId: '1',
    ementa: 'Ementa Desenvolvimento Web - Turno Noite',
    instrutorId: '3',
    instrutor: 'João Santos',
    status: 'em_andamento',
    dataInicio: '2024-03-01',
    dataFim: '2024-06-30',
    horario: '19:00 - 22:00',
    diasSemana: ['Segunda', 'Quarta'],
    sala: 'Sala 101',
    vagasTotal: 20,
    vagasOcupadas: 15,
    alunos: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
    dataCriacao: '2024-02-01',
  },
  {
    id: '2',
    codigo: 'WEB-2024-02',
    ementaId: '1',
    ementa: 'Ementa Desenvolvimento Web - Turno Noite',
    instrutorId: '3',
    instrutor: 'João Santos',
    status: 'planejada',
    dataInicio: '2024-07-01',
    dataFim: '2024-10-31',
    horario: '14:00 - 17:00',
    diasSemana: ['Terça', 'Quinta'],
    sala: 'Sala 102',
    vagasTotal: 20,
    vagasOcupadas: 5,
    alunos: ['16', '17', '18', '19', '20'],
    dataCriacao: '2024-05-15',
  },
  {
    id: '3',
    codigo: 'UX-2024-01',
    ementaId: '2',
    ementa: 'Ementa Design UX/UI - Completo',
    instrutorId: '4',
    instrutor: 'Ana Paula Oliveira',
    status: 'em_andamento',
    dataInicio: '2024-04-01',
    dataFim: '2024-07-15',
    horario: '09:00 - 12:00',
    diasSemana: ['Segunda', 'Quarta', 'Sexta'],
    sala: 'Sala 201',
    vagasTotal: 20,
    vagasOcupadas: 18,
    alunos: ['38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55'],
    dataCriacao: '2024-03-01',
  },
  {
    id: '4',
    codigo: 'PY-2024-01',
    ementaId: '3',
    ementa: 'Ementa Python Data Science - Intensivo',
    instrutorId: '5',
    instrutor: 'Carlos Mendes',
    status: 'em_andamento',
    dataInicio: '2024-05-01',
    dataFim: '2024-08-31',
    horario: '19:00 - 22:00',
    diasSemana: ['Terça', 'Quinta'],
    sala: 'Lab 301',
    vagasTotal: 20,
    vagasOcupadas: 12,
    alunos: ['56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67'],
    dataCriacao: '2024-04-01',
  },
];

// Alunos Mock - Turma WEB-2024-01 do instrutor João Santos (ID 3)
export const mockAlunos: Aluno[] = [
  {
    id: '1',
    nome: 'Pedro Henrique Costa',
    email: 'pedro.costa@email.com',
    telefone: '(11) 99876-5432',
    cpf: '123.456.789-00',
    dataNascimento: '1998-05-15',
    endereco: {
      rua: 'Rua das Flores',
      numero: '123',
      bairro: 'Capão Redondo',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05860000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-20',
    contatoEmergencia: {
      nome: 'Maria Helena Costa',
      telefone: '(11) 98765-4321',
      parentesco: 'Mãe',
    },
    alergias: 'Nenhuma alergia conhecida',
  },
  {
    id: '2',
    nome: 'Juliana Fernandes',
    email: 'juliana.fernandes@email.com',
    telefone: '(11) 99876-5433',
    cpf: '234.567.890-11',
    dataNascimento: '2000-08-22',
    endereco: {
      rua: 'Avenida dos Trabalhadores',
      numero: '456',
      bairro: 'Jardim Ângela',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05833000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-21',
    contatoEmergencia: {
      nome: 'Carlos Fernandes',
      telefone: '(11) 97654-3210',
      parentesco: 'Pai',
    },
    alergias: 'Alergia a frutos do mar',
    deficiencias: 'Usa óculos para correção visual',
  },
  {
    id: '3',
    nome: 'Lucas Almeida',
    email: 'lucas.almeida@email.com',
    telefone: '(11) 99876-5434',
    cpf: '345.678.901-22',
    dataNascimento: '1999-11-10',
    endereco: {
      rua: 'Rua São João',
      numero: '789',
      bairro: 'Cidade Tiradentes',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '08470000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-22',
    contatoEmergencia: {
      nome: 'Ana Paula Almeida',
      telefone: '(11) 96543-2109',
      parentesco: 'Mãe',
    },
    deficiencias: 'Asma leve - necessita inalador em emergências',
  },
  {
    id: '4',
    nome: 'Mariana Santos',
    email: 'mariana.santos@email.com',
    telefone: '(11) 99876-5435',
    cpf: '456.789.012-33',
    dataNascimento: '2001-03-18',
    endereco: {
      rua: 'Rua da Esperança',
      numero: '234',
      bairro: 'Brasilândia',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '02800000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-23',
    contatoEmergencia: {
      nome: 'Roberto Santos',
      telefone: '(11) 95432-1098',
      parentesco: 'Pai',
    },
    alergias: 'Alergia a lactose e amendoim',
  },
  {
    id: '5',
    nome: 'Rafael Oliveira',
    email: 'rafael.oliveira@email.com',
    telefone: '(11) 99876-5436',
    cpf: '567.890.123-44',
    dataNascimento: '1997-07-25',
    endereco: {
      rua: 'Avenida Central',
      numero: '567',
      bairro: 'Grajaú',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04850000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    contatoEmergencia: {
      nome: 'Silvia Oliveira',
      telefone: '(11) 94321-0987',
      parentesco: 'Mãe',
    },
  },
  {
    id: '6',
    nome: 'Camila Rodrigues',
    email: 'camila.rodrigues@email.com',
    telefone: '(11) 99876-5437',
    cpf: '678.901.234-55',
    dataNascimento: '2002-01-12',
    endereco: {
      rua: 'Rua das Palmeiras',
      numero: '890',
      bairro: 'Parelheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04890000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    contatoEmergencia: {
      nome: 'Fernanda Rodrigues',
      telefone: '(11) 93210-9876',
      parentesco: 'Irmã',
    },
    alergias: 'Alergia a glúten',
    deficiencias: 'Mobilidade reduzida - usa cadeira de rodas',
  },
  {
    id: '7',
    nome: 'Thiago Souza',
    email: 'thiago.souza@email.com',
    telefone: '(11) 99876-5438',
    cpf: '789.012.345-66',
    dataNascimento: '1999-04-30',
    endereco: {
      rua: 'Rua do Comércio',
      numero: '321',
      bairro: 'São Miguel Paulista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '08010000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    contatoEmergencia: {
      nome: 'Marcelo Souza',
      telefone: '(11) 92109-8765',
      parentesco: 'Tio',
    },
    deficiencias: 'Diabetes tipo 1 - necessita insulina',
  },
  {
    id: '8',
    nome: 'Amanda Silva',
    email: 'amanda.silva@email.com',
    telefone: '(11) 99876-5439',
    cpf: '890.123.456-77',
    dataNascimento: '2000-09-18',
    endereco: {
      rua: 'Avenida Principal',
      numero: '654',
      bairro: 'Itaquera',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '08220000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    contatoEmergencia: {
      nome: 'Paulo Silva',
      telefone: '(11) 91098-7654',
      parentesco: 'Pai',
    },
    alergias: 'Alergia a medicamentos à base de penicilina',
  },
  {
    id: '9',
    nome: 'Bruno Costa',
    email: 'bruno.costa@email.com',
    telefone: '(11) 99876-5440',
    cpf: '901.234.567-88',
    dataNascimento: '1998-11-25',
    endereco: {
      rua: 'Rua Nova',
      numero: '987',
      bairro: 'Capão Redondo',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05860100',
    },
    status: 'evadido',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-25',
    contatoEmergencia: {
      nome: 'Sandra Costa',
      telefone: '(11) 90987-6543',
      parentesco: 'Mãe',
    },
  },
  {
    id: '10',
    nome: 'Letícia Martins',
    email: 'leticia.martins@email.com',
    telefone: '(11) 99876-5441',
    cpf: '012.345.678-99',
    dataNascimento: '2001-06-14',
    endereco: {
      rua: 'Rua das Acácias',
      numero: '147',
      bairro: 'Jardim São Luís',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05813000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    contatoEmergencia: {
      nome: 'Lúcia Martins',
      telefone: '(11) 89876-5432',
      parentesco: 'Avó',
    },
    alergias: 'Alergia a pólen e ácaros',
    deficiencias: 'Deficiência auditiva parcial - usa aparelho auditivo',
  },
  {
    id: '11',
    nome: 'Gabriel Santos',
    email: 'gabriel.santos@email.com',
    telefone: '(11) 99876-5442',
    cpf: '123.456.789-10',
    dataNascimento: '1997-03-22',
    endereco: {
      rua: 'Rua do Progresso',
      numero: '258',
      bairro: 'Jardim Ângela',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05833100',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    contatoEmergencia: {
      nome: 'Roberto Santos',
      telefone: '(11) 98234-5678',
      parentesco: 'Pai',
    },
    alergias: 'Alergia a pólen e ácaros',
  },
  {
    id: '12',
    nome: 'Patrícia Lima',
    email: 'patricia.lima@email.com',
    telefone: '(11) 99876-5443',
    cpf: '234.567.890-21',
    dataNascimento: '2002-07-08',
    endereco: {
      rua: 'Avenida das Nações',
      numero: '369',
      bairro: 'Cidade Tiradentes',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '08470100',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    deficiencias: 'TDAH - em tratamento com acompanhamento psicológico',
  },
  {
    id: '13',
    nome: 'Fernando Rocha',
    email: 'fernando.rocha@email.com',
    telefone: '(11) 99876-5444',
    cpf: '345.678.901-32',
    dataNascimento: '2000-02-15',
    endereco: {
      rua: 'Rua das Orquídeas',
      numero: '512',
      bairro: 'Vila das Belezas',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05840000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    alergias: 'Alergia a medicamentos anti-inflamatórios',
  },
  {
    id: '14',
    nome: 'Carolina Mendes',
    email: 'carolina.mendes@email.com',
    telefone: '(11) 99876-5445',
    cpf: '456.789.012-43',
    dataNascimento: '1999-09-30',
    endereco: {
      rua: 'Avenida do Estado',
      numero: '1234',
      bairro: 'Jabaquara',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04270000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    contatoEmergencia: {
      nome: 'Ana Paula Mendes',
      telefone: '(11) 97654-3210',
      parentesco: 'Mãe',
    },
    deficiencias: 'Epilepsia controlada com medicação',
  },
  {
    id: '15',
    nome: 'Diego Alves',
    email: 'diego.alves@email.com',
    telefone: '(11) 99876-5446',
    cpf: '567.890.123-54',
    dataNascimento: '2001-11-20',
    endereco: {
      rua: 'Rua São Bento',
      numero: '678',
      bairro: 'Campo Limpo',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05777000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-02-24',
    alergias: 'Nenhuma alergia conhecida',
  },
  // Turma WEB-2024-02 (Planejada)
  {
    id: '16',
    nome: 'Renata Oliveira',
    email: 'renata.oliveira@email.com',
    telefone: '(11) 99876-5447',
    cpf: '678.901.234-65',
    dataNascimento: '2002-03-10',
    endereco: {
      rua: 'Rua das Laranjeiras',
      numero: '234',
      bairro: 'Pirituba',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '02950000',
    },
    status: 'ativo',
    turmaId: '2',
    turma: 'WEB-2024-02',
    dataMatricula: '2024-06-15',
    contatoEmergencia: {
      nome: 'José Carlos Oliveira',
      telefone: '(11) 98123-4567',
      parentesco: 'Pai',
    },
    alergias: 'Alergia a glúten - doença celíaca',
  },
  {
    id: '17',
    nome: 'Paulo Henrique',
    email: 'paulo.henrique@email.com',
    telefone: '(11) 99876-5448',
    cpf: '789.012.345-76',
    dataNascimento: '2000-05-25',
    endereco: {
      rua: 'Avenida Paulista',
      numero: '2000',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01310000',
    },
    status: 'ativo',
    turmaId: '2',
    turma: 'WEB-2024-02',
    dataMatricula: '2024-06-15',
    deficiencias: 'Deficiência visual parcial - usa óculos de grau alto',
  },
  {
    id: '18',
    nome: 'Vanessa Santos',
    email: 'vanessa.santos@email.com',
    telefone: '(11) 99876-5449',
    cpf: '890.123.456-87',
    dataNascimento: '1998-07-18',
    endereco: {
      rua: 'Rua da Glória',
      numero: '456',
      bairro: 'Liberdade',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01510000',
    },
    status: 'ativo',
    turmaId: '2',
    turma: 'WEB-2024-02',
    dataMatricula: '2024-06-15',
    alergias: 'Alergia a picadas de insetos - reação grave',
    contatoEmergencia: {
      nome: 'Luciana Santos',
      telefone: '(11) 96543-2109',
      parentesco: 'Irmã',
    },
  },
  {
    id: '19',
    nome: 'Rodrigo Cardoso',
    email: 'rodrigo.cardoso@email.com',
    telefone: '(11) 99876-5450',
    cpf: '901.234.567-98',
    dataNascimento: '2001-12-05',
    endereco: {
      rua: 'Rua Vergueiro',
      numero: '789',
      bairro: 'Vila Mariana',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04101000',
    },
    status: 'ativo',
    turmaId: '2',
    turma: 'WEB-2024-02',
    dataMatricula: '2024-06-15',
    deficiencias: 'Transtorno do Espectro Autista (TEA) - nível 1',
  },
  {
    id: '20',
    nome: 'Beatriz Souza',
    email: 'beatriz.souza@email.com',
    telefone: '(11) 99876-5451',
    cpf: '012.345.678-09',
    dataNascimento: '1999-08-14',
    endereco: {
      rua: 'Avenida Ipiranga',
      numero: '321',
      bairro: 'República',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01046000',
    },
    status: 'ativo',
    turmaId: '2',
    turma: 'WEB-2024-02',
    dataMatricula: '2024-06-15',
    contatoEmergencia: {
      nome: 'Regina Souza',
      telefone: '(11) 95432-1098',
      parentesco: 'Mãe',
    },
    alergias: 'Nenhuma alergia conhecida',
  },
  // Alunos de outras turmas (diferentes instrutores)
  {
    id: '21',
    nome: 'Isabela Costa',
    email: 'isabela.costa@email.com',
    telefone: '(11) 99876-5452',
    cpf: '123.456.789-20',
    dataNascimento: '2000-04-22',
    endereco: {
      rua: 'Rua Augusta',
      numero: '1500',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01305000',
    },
    status: 'ativo',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-07-10',
  },
  {
    id: '22',
    nome: 'Miguel Ferreira',
    email: 'miguel.ferreira@email.com',
    telefone: '(11) 99876-5453',
    cpf: '234.567.890-31',
    dataNascimento: '2002-06-08',
    endereco: {
      rua: 'Alameda Santos',
      numero: '900',
      bairro: 'Jardins',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01419000',
    },
    status: 'ativo',
    turmaId: '4',
    turma: 'PY-2024-01',
    dataMatricula: '2024-08-05',
  },
  // Alunos adicionados para visualização de dados no gráfico (últimos 6 meses)
  // Junho 2024
  {
    id: '68',
    nome: 'Lucas Martins',
    email: 'lucas.martins@email.com',
    telefone: '(11) 99888-7777',
    cpf: '789.012.345-67',
    dataNascimento: '2001-04-10',
    endereco: {
      rua: 'Rua das Palmeiras',
      numero: '890',
      bairro: 'Tatuapé',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '03070000',
    },
    status: 'concluido',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-06-05',
    contatoEmergencia: {
      nome: 'Ana Martins',
      telefone: '(11) 98888-6666',
      parentesco: 'Mãe',
    },
  },
  {
    id: '69',
    nome: 'Beatriz Santos',
    email: 'beatriz.santos@email.com',
    telefone: '(11) 99777-6666',
    cpf: '890.123.456-78',
    dataNascimento: '1999-09-20',
    endereco: {
      rua: 'Avenida Paulista',
      numero: '1500',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01310000',
    },
    status: 'concluido',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-06-12',
  },
  {
    id: '70',
    nome: 'Gabriel Oliveira',
    email: 'gabriel.oliveira@email.com',
    telefone: '(11) 99666-5555',
    cpf: '901.234.567-89',
    dataNascimento: '2002-01-15',
    endereco: {
      rua: 'Rua da Consolação',
      numero: '2300',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01301000',
    },
    status: 'evadido',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-06-18',
  },
  // Julho 2024
  {
    id: '71',
    nome: 'Larissa Costa',
    email: 'larissa.costa@email.com',
    telefone: '(11) 99555-4444',
    cpf: '012.345.678-90',
    dataNascimento: '2000-03-08',
    endereco: {
      rua: 'Rua Oscar Freire',
      numero: '600',
      bairro: 'Jardins',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01426000',
    },
    status: 'concluido',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-07-03',
  },
  {
    id: '72',
    nome: 'Rafael Lima',
    email: 'rafael.lima@email.com',
    telefone: '(11) 99444-3333',
    cpf: '123.456.789-01',
    dataNascimento: '1998-11-25',
    endereco: {
      rua: 'Avenida Rebouças',
      numero: '3000',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05401000',
    },
    status: 'concluido',
    turmaId: '4',
    turma: 'PY-2024-01',
    dataMatricula: '2024-07-10',
  },
  {
    id: '73',
    nome: 'Camila Rocha',
    email: 'camila.rocha@email.com',
    telefone: '(11) 99333-2222',
    cpf: '234.567.890-12',
    dataNascimento: '2001-07-14',
    endereco: {
      rua: 'Rua Augusta',
      numero: '1200',
      bairro: 'Cerqueira César',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01304000',
    },
    status: 'evadido',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-07-15',
  },
  {
    id: '74',
    nome: 'Thiago Alves',
    email: 'thiago.alves@email.com',
    telefone: '(11) 99222-1111',
    cpf: '345.678.901-23',
    dataNascimento: '1999-05-30',
    endereco: {
      rua: 'Rua Haddock Lobo',
      numero: '800',
      bairro: 'Cerqueira César',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01414000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-07-22',
  },
  // Agosto 2024
  {
    id: '75',
    nome: 'Amanda Ribeiro',
    email: 'amanda.ribeiro@email.com',
    telefone: '(11) 99111-0000',
    cpf: '456.789.012-34',
    dataNascimento: '2002-08-05',
    endereco: {
      rua: 'Alameda Jaú',
      numero: '1500',
      bairro: 'Jardim Paulista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01420000',
    },
    status: 'concluido',
    turmaId: '4',
    turma: 'PY-2024-01',
    dataMatricula: '2024-08-01',
  },
  {
    id: '76',
    nome: 'Felipe Barbosa',
    email: 'felipe.barbosa@email.com',
    telefone: '(11) 99000-9999',
    cpf: '567.890.123-45',
    dataNascimento: '2000-12-12',
    endereco: {
      rua: 'Rua dos Três Irmãos',
      numero: '400',
      bairro: 'Vila Progredior',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05615000',
    },
    status: 'concluido',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-08-08',
  },
  {
    id: '77',
    nome: 'Isabela Ferreira',
    email: 'isabela.ferreira@email.com',
    telefone: '(11) 98999-8888',
    cpf: '678.901.234-56',
    dataNascimento: '2001-02-28',
    endereco: {
      rua: 'Rua Fradique Coutinho',
      numero: '1000',
      bairro: 'Vila Madalena',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05416000',
    },
    status: 'ativo',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-08-15',
  },
  {
    id: '78',
    nome: 'Vinicius Cardoso',
    email: 'vinicius.cardoso@email.com',
    telefone: '(11) 98888-7777',
    cpf: '789.012.345-67',
    dataNascimento: '1998-06-18',
    endereco: {
      rua: 'Rua Girassol',
      numero: '200',
      bairro: 'Vila Madalena',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05433000',
    },
    status: 'evadido',
    turmaId: '4',
    turma: 'PY-2024-01',
    dataMatricula: '2024-08-20',
  },
  // Setembro 2024
  {
    id: '79',
    nome: 'Patricia Gomes',
    email: 'patricia.gomes@email.com',
    telefone: '(11) 98777-6666',
    cpf: '890.123.456-78',
    dataNascimento: '2000-10-03',
    endereco: {
      rua: 'Avenida Angélica',
      numero: '2500',
      bairro: 'Higienópolis',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01228000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-09-02',
  },
  {
    id: '80',
    nome: 'Bruno Dias',
    email: 'bruno.dias@email.com',
    telefone: '(11) 98666-5555',
    cpf: '901.234.567-89',
    dataNascimento: '1999-04-22',
    endereco: {
      rua: 'Rua dos Pinheiros',
      numero: '700',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05422000',
    },
    status: 'ativo',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-09-10',
  },
  {
    id: '81',
    nome: 'Fernanda Castro',
    email: 'fernanda.castro@email.com',
    telefone: '(11) 98555-4444',
    cpf: '012.345.678-90',
    dataNascimento: '2002-09-15',
    endereco: {
      rua: 'Alameda Campinas',
      numero: '900',
      bairro: 'Jardim Paulista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01404000',
    },
    status: 'evadido',
    turmaId: '4',
    turma: 'PY-2024-01',
    dataMatricula: '2024-09-18',
  },
  {
    id: '82',
    nome: 'Rodrigo Mendes',
    email: 'rodrigo.mendes@email.com',
    telefone: '(11) 98444-3333',
    cpf: '123.456.789-01',
    dataNascimento: '2001-11-08',
    endereco: {
      rua: 'Rua Bela Cintra',
      numero: '1800',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01415000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-09-25',
  },
  // Outubro 2024
  {
    id: '83',
    nome: 'Juliana Souza',
    email: 'juliana.souza@email.com',
    telefone: '(11) 98333-2222',
    cpf: '234.567.890-12',
    dataNascimento: '2000-01-20',
    endereco: {
      rua: 'Rua Estados Unidos',
      numero: '1500',
      bairro: 'Jardim América',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01427000',
    },
    status: 'ativo',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-10-05',
  },
  {
    id: '84',
    nome: 'Marcos Pereira',
    email: 'marcos.pereira@email.com',
    telefone: '(11) 98222-1111',
    cpf: '345.678.901-23',
    dataNascimento: '1999-07-30',
    endereco: {
      rua: 'Avenida Ipiranga',
      numero: '2000',
      bairro: 'República',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01046000',
    },
    status: 'ativo',
    turmaId: '4',
    turma: 'PY-2024-01',
    dataMatricula: '2024-10-12',
  },
  {
    id: '85',
    nome: 'Aline Moreira',
    email: 'aline.moreira@email.com',
    telefone: '(11) 98111-0000',
    cpf: '456.789.012-34',
    dataNascimento: '2002-03-18',
    endereco: {
      rua: 'Rua da Mooca',
      numero: '3000',
      bairro: 'Mooca',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '03104000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-10-20',
  },
  // Novembro 2024
  {
    id: '86',
    nome: 'Diego Carvalho',
    email: 'diego.carvalho@email.com',
    telefone: '(11) 98000-9999',
    cpf: '567.890.123-45',
    dataNascimento: '2001-05-25',
    endereco: {
      rua: 'Rua Vergueiro',
      numero: '5000',
      bairro: 'Vila Mariana',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04101000',
    },
    status: 'ativo',
    turmaId: '3',
    turma: 'UX-2024-01',
    dataMatricula: '2024-11-02',
  },
  {
    id: '87',
    nome: 'Mariana Lopes',
    email: 'mariana.lopes@email.com',
    telefone: '(11) 97999-8888',
    cpf: '678.901.234-56',
    dataNascimento: '2000-08-12',
    endereco: {
      rua: 'Avenida São João',
      numero: '1000',
      bairro: 'Centro',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01035000',
    },
    status: 'ativo',
    turmaId: '4',
    turma: 'PY-2024-01',
    dataMatricula: '2024-11-08',
  },
  {
    id: '88',
    nome: 'Leonardo Silva',
    email: 'leonardo.silva@email.com',
    telefone: '(11) 97888-7777',
    cpf: '789.012.345-67',
    dataNascimento: '1999-12-01',
    endereco: {
      rua: 'Rua Pamplona',
      numero: '800',
      bairro: 'Jardim Paulista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01405000',
    },
    status: 'ativo',
    turmaId: '1',
    turma: 'WEB-2024-01',
    dataMatricula: '2024-11-15',
  },
];

// Interessados Mock
export const mockInteressados: Interessado[] = [
  // Voluntários
  {
    id: '1',
    tipo: 'voluntario',
    nome: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    telefone: '(11) 99999-1111',
    idade: 28,
    dataNascimento: '1996-03-15',
    genero: 'feminino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Tecnologia',
    endereco: {
      rua: 'Rua dos Voluntários',
      numero: '100',
      bairro: 'Vila Mariana',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04015000',
    },
    motivoVoluntariado: 'Quero contribuir com meus conhecimentos em tecnologia para ajudar pessoas a aprenderem programação e terem melhores oportunidades no mercado de trabalho.',
    habilidadesExperiencia: 'Desenvolvedora Full Stack com 5 anos de experiência em React, Node.js e banco de dados. Experiência em mentoria de desenvolvedores júnior.',
    nivelDisponibilidade: '8 horas por semana',
    experienciaVoluntariado: true,
    detalhesExperienciaVoluntariado: 'Fui voluntária em uma ONG de ensino de programação para jovens de baixa renda por 1 ano. Foi uma experiência muito gratificante ver o progresso dos alunos.',
    corRaca: 'parda',
    deficienciaFisica: false,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    status: 'novo',
    dataRegistro: '2024-10-28',
    origem: 'Instagram',
  },
  {
    id: '2',
    tipo: 'voluntario',
    nome: 'Ricardo Souza',
    email: 'ricardo.souza@email.com',
    telefone: '(11) 99999-2222',
    idade: 35,
    dataNascimento: '1989-07-22',
    genero: 'masculino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Educação',
    endereco: {
      rua: 'Avenida Brigadeiro Faria Lima',
      numero: '2000',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01452000',
    },
    motivoVoluntariado: 'Sempre acreditei no poder da educação para transformar vidas. Quero usar minha experiência como professor para ajudar mais pessoas.',
    habilidadesExperiencia: 'Professor de matemática com 10 anos de experiência. Especialista em metodologias ativas e educação inclusiva.',
    nivelDisponibilidade: 'Mais de 10 horas por semana',
    experienciaVoluntariado: true,
    detalhesExperienciaVoluntariado: 'Participei de projetos de reforço escolar em comunidades carentes e também dei aulas em prisões.',
    corRaca: 'branca',
    deficienciaFisica: false,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    status: 'contatado',
    dataRegistro: '2024-10-25',
    dataContato: '2024-10-26',
    origem: 'Google',
  },
  {
    id: '3',
    tipo: 'voluntario',
    nome: 'Camila Rodrigues',
    email: 'camila.rodrigues@email.com',
    telefone: '(11) 99999-3333',
    idade: 24,
    dataNascimento: '2000-11-08',
    genero: 'feminino',
    escolaridade: 'superior_incompleto',
    cursoInteresse: 'Design',
    endereco: {
      rua: 'Rua Augusta',
      numero: '500',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01305000',
    },
    motivoVoluntariado: 'Como designer, quero usar minhas habilidades para ajudar organizações sociais a terem uma comunicação visual mais efetiva e impactante.',
    habilidadesExperiencia: 'Designer UX/UI com experiência em Figma, Adobe XD e ferramentas de prototipagem. Conhecimentos em design thinking e acessibilidade.',
    nivelDisponibilidade: '6 horas por semana',
    experienciaVoluntariado: false,
    corRaca: 'preta',
    deficienciaFisica: false,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    status: 'matriculado',
    dataRegistro: '2024-10-30',
    dataContato: '2024-11-01',
    origem: 'Indicação',
  },
  {
    id: '11',
    tipo: 'voluntario',
    nome: 'Paulo Henrique Costa',
    email: 'paulo.costa@email.com',
    telefone: '(11) 98888-4444',
    idade: 42,
    dataNascimento: '1982-05-18',
    genero: 'masculino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Administração',
    endereco: {
      rua: 'Rua Vergueiro',
      numero: '1500',
      bairro: 'Liberdade',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01504000',
    },
    motivoVoluntariado: 'Tenho experiência em gestão empresarial e quero ajudar ONGs a se organizarem melhor e alcançarem seus objetivos de forma mais eficiente.',
    habilidadesExperiencia: 'Administrador com MBA em Gestão de Projetos. 15 anos de experiência em gestão empresarial, planejamento estratégico e captação de recursos.',
    nivelDisponibilidade: '4 horas por semana',
    experienciaVoluntariado: true,
    detalhesExperienciaVoluntariado: 'Fui conselheiro fiscal de uma ONG de proteção animal por 3 anos.',
    corRaca: 'branca',
    deficienciaFisica: true,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    especificacaoDeficiencia: 'Uso cadeira de rodas devido a lesão medular',
    status: 'matriculado',
    dataRegistro: '2024-09-15',
    dataContato: '2024-09-16',
    origem: 'LinkedIn',
  },
  {
    id: '12',
    tipo: 'voluntario',
    nome: 'Mariana Santos Oliveira',
    email: 'mariana.santos.o@email.com',
    telefone: '(11) 97777-5555',
    idade: 31,
    dataNascimento: '1993-02-28',
    genero: 'feminino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Marketing',
    endereco: {
      rua: 'Alameda Santos',
      numero: '800',
      bairro: 'Jardins',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01418000',
    },
    motivoVoluntariado: 'Acredito que boas estratégias de marketing podem amplificar o impacto social de organizações que fazem a diferença.',
    habilidadesExperiencia: 'Especialista em marketing digital, mídias sociais e comunicação. Experiência em campanhas de captação de recursos e engajamento.',
    nivelDisponibilidade: '6 horas por semana',
    experienciaVoluntariado: false,
    corRaca: 'indigena',
    etnia: 'Guarani',
    deficienciaFisica: false,
    deficienciaIntelectual: false,
    necessidadeEspecial: false,
    status: 'contatado',
    dataRegistro: '2024-11-05',
    dataContato: '2024-11-06',
    origem: 'Site',
  },
  // Alunos Interessados
  {
    id: '4',
    tipo: 'aluno',
    nome: 'João Pedro Silva',
    email: 'joao.pedro@email.com',
    telefone: '(11) 98765-4321',
    idade: 17,
    dataNascimento: '2007-05-15',
    cpf: '12345678901',
    genero: 'masculino',
    escolaridade: 'medio_incompleto',
    cursoInteresse: 'Desenvolvimento Web Full Stack',
    endereco: {
      rua: 'Rua das Flores',
      numero: '123',
      complemento: 'Apt 45',
      bairro: 'Centro',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234567',
    },
    responsavel: {
      nome: 'Maria Silva',
      parentesco: 'Mãe',
    },
    contatoEmergencia: {
      nome: 'José Silva',
      telefone: '(11) 98765-1234',
      parentesco: 'Pai',
    },
    corRaca: 'parda',
    alergias: 'Nenhuma',
    deficiencias: 'Nenhuma',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: true,
      outro: false,
    },
    status: 'novo',
    dataRegistro: '2024-11-01',
    origem: 'Site',
  },
  {
    id: '5',
    tipo: 'aluno',
    nome: 'Ana Carolina Oliveira',
    email: 'ana.carolina@email.com',
    telefone: '(11) 97654-3210',
    idade: 22,
    dataNascimento: '2002-08-20',
    cpf: '98765432109',
    genero: 'feminino',
    escolaridade: 'superior_incompleto',
    cursoInteresse: 'Design UX/UI',
    endereco: {
      rua: 'Avenida Paulista',
      numero: '1000',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01310100',
    },
    contatoEmergencia: {
      nome: 'Carla Oliveira',
      telefone: '(11) 97654-9876',
      parentesco: 'Mãe',
    },
    corRaca: 'branca',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: false,
      outro: false,
    },
    status: 'contatado',
    dataRegistro: '2024-10-28',
    dataContato: '2024-10-29',
    origem: 'Instagram',
  },
  {
    id: '6',
    tipo: 'aluno',
    nome: 'Lucas Gabriel Santos',
    email: 'lucas.gabriel@email.com',
    telefone: '(11) 96543-2109',
    idade: 19,
    dataNascimento: '2005-03-10',
    cpf: '45678912345',
    genero: 'masculino',
    escolaridade: 'medio_completo',
    cursoInteresse: 'Python para Data Science',
    endereco: {
      rua: 'Rua da Consolação',
      numero: '456',
      complemento: 'Casa 2',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01302000',
    },
    contatoEmergencia: {
      nome: 'Pedro Santos',
      telefone: '(11) 96543-7890',
      parentesco: 'Irmão',
    },
    corRaca: 'preta',
    alergias: 'Lactose',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: false,
      comprovanteResidencia: true,
      outro: false,
    },
    status: 'novo',
    dataRegistro: '2024-11-02',
    origem: 'Facebook',
  },
  {
    id: '7',
    tipo: 'aluno',
    nome: 'Beatriz Ferreira Costa',
    email: 'beatriz.ferreira@email.com',
    telefone: '(11) 95432-1098',
    idade: 25,
    dataNascimento: '1999-12-05',
    cpf: '78912345678',
    genero: 'feminino',
    escolaridade: 'superior_completo',
    cursoInteresse: 'Desenvolvimento Web Full Stack',
    endereco: {
      rua: 'Rua Augusta',
      numero: '789',
      bairro: 'Jardins',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01304000',
    },
    contatoEmergencia: {
      nome: 'Claudia Costa',
      telefone: '(11) 95432-5678',
      parentesco: 'Mãe',
    },
    corRaca: 'branca',
    deficiencias: 'Deficiência visual leve (usa óculos)',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: true,
      outro: true,
    },
    status: 'matriculado',
    dataRegistro: '2024-10-20',
    dataContato: '2024-10-21',
    origem: 'LinkedIn',
  },
  {
    id: '8',
    tipo: 'aluno',
    nome: 'Gabriel Henrique Alves',
    email: 'gabriel.alves@email.com',
    telefone: '(11) 94321-0987',
    idade: 16,
    dataNascimento: '2008-07-22',
    cpf: '32165498732',
    genero: 'masculino',
    escolaridade: 'medio_incompleto',
    cursoInteresse: 'Design UX/UI',
    endereco: {
      rua: 'Rua Oscar Freire',
      numero: '321',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01426000',
    },
    responsavel: {
      nome: 'Roberto Alves',
      parentesco: 'Pai',
    },
    contatoEmergencia: {
      nome: 'Fernanda Alves',
      telefone: '(11) 94321-4567',
      parentesco: 'Mãe',
    },
    corRaca: 'amarela',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: false,
      comprovanteEscolaridade: true,
      comprovanteResidencia: true,
      outro: false,
    },
    status: 'novo',
    dataRegistro: '2024-11-03',
    origem: 'Indicação',
  },
  {
    id: '9',
    tipo: 'aluno',
    nome: 'Juliana Martins Souza',
    email: 'juliana.martins@email.com',
    telefone: '(11) 93210-9876',
    idade: 20,
    dataNascimento: '2004-04-18',
    cpf: '65432178965',
    genero: 'feminino',
    escolaridade: 'superior_incompleto',
    cursoInteresse: 'Python para Data Science',
    endereco: {
      rua: 'Avenida Rebouças',
      numero: '987',
      complemento: 'Bloco B',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '05401000',
    },
    contatoEmergencia: {
      nome: 'Ricardo Souza',
      telefone: '(11) 93210-1234',
      parentesco: 'Tio',
    },
    corRaca: 'parda',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: false,
      outro: false,
    },
    status: 'contatado',
    dataRegistro: '2024-10-30',
    dataContato: '2024-10-31',
    origem: 'Google',
  },
  {
    id: '10',
    tipo: 'aluno',
    nome: 'Thiago Araújo Lima',
    email: 'thiago.araujo@email.com',
    telefone: '(11) 92109-8765',
    idade: 23,
    dataNascimento: '2001-09-30',
    cpf: '15975348621',
    genero: 'masculino',
    escolaridade: 'medio_completo',
    cursoInteresse: 'Desenvolvimento Web Full Stack',
    endereco: {
      rua: 'Rua Haddock Lobo',
      numero: '654',
      bairro: 'Cerqueira César',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01414000',
    },
    contatoEmergencia: {
      nome: 'Amanda Lima',
      telefone: '(11) 92109-3456',
      parentesco: 'Irmã',
    },
    corRaca: 'indigena',
    etnia: 'Guarani',
    alergias: 'Amendoim',
    informacoesCorretas: true,
    documentosEntregues: {
      identidade: true,
      comprovanteEscolaridade: true,
      comprovanteResidencia: true,
      outro: false,
    },
    status: 'desistente',
    dataRegistro: '2024-10-15',
    dataContato: '2024-10-16',
    origem: 'Site',
  },
];

// Diários de Aula Mock - Turma WEB-2024-01 do instrutor João Santos
export const mockDiarios: DiarioAula[] = [
  {
    id: '1',
    turmaId: '1',
    instrutorId: '3',
    aulaEmentaId: '1-1',
    aulaTitulo: 'Introdução ao Desenvolvimento Web',
    data: '2024-03-04',
    numeroAula: 1,
    tipo: 'teorica',
    conteudo: 'Abordamos a história da web, arquitetura cliente-servidor, protocolos HTTP/HTTPS. Apresentação do curso, objetivos de aprendizagem e metodologia de ensino.',
    resumo: 'Primeira aula com apresentação do curso e fundamentos sobre como a web funciona. Alunos demonstraram interesse e fizeram boas perguntas sobre a área.',
    presencas: [
      { alunoId: '1', alunoNome: 'Pedro Henrique Costa', status: 'presente' },
      { alunoId: '2', alunoNome: 'Juliana Fernandes', status: 'presente' },
      { alunoId: '3', alunoNome: 'Lucas Almeida', status: 'ausente' },
      { alunoId: '4', alunoNome: 'Mariana Santos', status: 'presente' },
      { alunoId: '5', alunoNome: 'Rafael Oliveira', status: 'presente' },
      { alunoId: '6', alunoNome: 'Camila Rodrigues', status: 'presente' },
      { alunoId: '7', alunoNome: 'Thiago Souza', status: 'presente' },
      { alunoId: '8', alunoNome: 'Amanda Silva', status: 'presente' },
      { alunoId: '9', alunoNome: 'Bruno Costa', status: 'presente' },
      { alunoId: '10', alunoNome: 'Letícia Martins', status: 'presente' },
      { alunoId: '11', alunoNome: 'Gabriel Santos', status: 'presente' },
      { alunoId: '12', alunoNome: 'Patrícia Lima', status: 'presente' },
      { alunoId: '13', alunoNome: 'Fernando Rocha', status: 'presente' },
      { alunoId: '14', alunoNome: 'Carolina Mendes', status: 'presente' },
      { alunoId: '15', alunoNome: 'Diego Alves', status: 'justificado', justificativa: 'Trabalho' },
    ],
    dataCriacao: '2024-03-04',
  },
  {
    id: '2',
    turmaId: '1',
    instrutorId: '3',
    aulaEmentaId: '1-2',
    aulaTitulo: 'HTML5 - Estrutura e Semântica',
    data: '2024-03-06',
    numeroAula: 2,
    tipo: 'teorica',
    conteudo: 'Estudamos tags básicas e semânticas do HTML5, criação de formulários e tabelas. Criamos a primeira página HTML com estrutura completa.',
    resumo: 'Aula prática com criação de estruturas HTML semânticas. Alunos criaram suas primeiras páginas web.',
    observacoes: 'Lucas compareceu e demonstrou interesse em recuperar o conteúdo perdido.',
    presencas: [
      { alunoId: '1', alunoNome: 'Pedro Henrique Costa', status: 'presente' },
      { alunoId: '2', alunoNome: 'Juliana Fernandes', status: 'presente' },
      { alunoId: '3', alunoNome: 'Lucas Almeida', status: 'presente' },
      { alunoId: '4', alunoNome: 'Mariana Santos', status: 'presente' },
      { alunoId: '5', alunoNome: 'Rafael Oliveira', status: 'presente' },
      { alunoId: '6', alunoNome: 'Camila Rodrigues', status: 'ausente' },
      { alunoId: '7', alunoNome: 'Thiago Souza', status: 'presente' },
      { alunoId: '8', alunoNome: 'Amanda Silva', status: 'presente' },
      { alunoId: '9', alunoNome: 'Bruno Costa', status: 'presente' },
      { alunoId: '10', alunoNome: 'Letícia Martins', status: 'presente' },
      { alunoId: '11', alunoNome: 'Gabriel Santos', status: 'presente' },
      { alunoId: '12', alunoNome: 'Patrícia Lima', status: 'presente' },
      { alunoId: '13', alunoNome: 'Fernando Rocha', status: 'presente' },
      { alunoId: '14', alunoNome: 'Carolina Mendes', status: 'presente' },
      { alunoId: '15', alunoNome: 'Diego Alves', status: 'presente' },
    ],
    dataCriacao: '2024-03-06',
  },
  {
    id: '3',
    turmaId: '1',
    instrutorId: '3',
    aulaEmentaId: '1-3',
    aulaTitulo: 'CSS3 - Estilização e Layout',
    data: '2024-03-11',
    numeroAula: 3,
    tipo: 'pratica',
    conteudo: 'Aplicação de estilos CSS, criação de layouts responsivos com Flexbox e Grid. Exercícios práticos de estilização de páginas HTML.',
    resumo: 'Exercícios práticos de estilização e layout responsivo. Alunos criaram seus primeiros layouts responsivos.',
    observacoes: 'Alunos demonstraram boa compreensão dos conceitos de flexbox. Mariana e Rafael se destacaram nos exercícios.',
    presencas: [
      { alunoId: '1', alunoNome: 'Pedro Henrique Costa', status: 'presente' },
      { alunoId: '2', alunoNome: 'Juliana Fernandes', status: 'presente' },
      { alunoId: '3', alunoNome: 'Lucas Almeida', status: 'presente' },
      { alunoId: '4', alunoNome: 'Mariana Santos', status: 'presente' },
      { alunoId: '5', alunoNome: 'Rafael Oliveira', status: 'presente' },
      { alunoId: '6', alunoNome: 'Camila Rodrigues', status: 'justificado', justificativa: 'Consulta médica' },
      { alunoId: '7', alunoNome: 'Thiago Souza', status: 'presente' },
      { alunoId: '8', alunoNome: 'Amanda Silva', status: 'presente' },
      { alunoId: '9', alunoNome: 'Bruno Costa', status: 'presente' },
      { alunoId: '10', alunoNome: 'Letícia Martins', status: 'presente' },
      { alunoId: '11', alunoNome: 'Gabriel Santos', status: 'presente' },
      { alunoId: '12', alunoNome: 'Patrícia Lima', status: 'presente' },
      { alunoId: '13', alunoNome: 'Fernando Rocha', status: 'presente' },
      { alunoId: '14', alunoNome: 'Carolina Mendes', status: 'ausente' },
      { alunoId: '15', alunoNome: 'Diego Alves', status: 'presente' },
    ],
    dataCriacao: '2024-03-11',
  },
  {
    id: '4',
    turmaId: '1',
    instrutorId: '3',
    aulaEmentaId: '1-4',
    aulaTitulo: 'JavaScript Fundamentos',
    data: '2024-03-13',
    numeroAula: 4,
    tipo: 'teorica',
    conteudo: 'Introdução ao JavaScript: variáveis, tipos de dados, estruturas de controle e funções. Manipulação básica do DOM.',
    resumo: 'Primeira aula de JavaScript. Abordamos os fundamentos da linguagem e criamos interações simples com a página.',
    observacoes: 'Bruno demonstrou dificuldade em acompanhar o ritmo. Precisa de acompanhamento individual.',
    presencas: [
      { alunoId: '1', alunoNome: 'Pedro Henrique Costa', status: 'presente' },
      { alunoId: '2', alunoNome: 'Juliana Fernandes', status: 'presente' },
      { alunoId: '3', alunoNome: 'Lucas Almeida', status: 'ausente' },
      { alunoId: '4', alunoNome: 'Mariana Santos', status: 'presente' },
      { alunoId: '5', alunoNome: 'Rafael Oliveira', status: 'presente' },
      { alunoId: '6', alunoNome: 'Camila Rodrigues', status: 'presente' },
      { alunoId: '7', alunoNome: 'Thiago Souza', status: 'presente' },
      { alunoId: '8', alunoNome: 'Amanda Silva', status: 'presente' },
      { alunoId: '9', alunoNome: 'Bruno Costa', status: 'presente' },
      { alunoId: '10', alunoNome: 'Letícia Martins', status: 'presente' },
      { alunoId: '11', alunoNome: 'Gabriel Santos', status: 'presente' },
      { alunoId: '12', alunoNome: 'Patrícia Lima', status: 'presente' },
      { alunoId: '13', alunoNome: 'Fernando Rocha', status: 'presente' },
      { alunoId: '14', alunoNome: 'Carolina Mendes', status: 'presente' },
      { alunoId: '15', alunoNome: 'Diego Alves', status: 'presente' },
    ],
    dataCriacao: '2024-03-13',
  },
  {
    id: '5',
    turmaId: '1',
    instrutorId: '3',
    aulaEmentaId: '1-5',
    aulaTitulo: 'Avaliação Módulo Front-end',
    data: '2024-03-18',
    numeroAula: 5,
    tipo: 'avaliacao',
    conteudo: 'Avaliação teórica e prática sobre HTML5, CSS3 e JavaScript. Exercício prático de criação de página web responsiva com interação.',
    resumo: 'Avaliação do módulo front-end. A maioria dos alunos demonstrou bom domínio dos conceitos.',
    observacoes: 'Pedro, Mariana e Rafael tiveram desempenho excelente. Bruno precisará de reforço antes do próximo módulo.',
    presencas: [
      { alunoId: '1', alunoNome: 'Pedro Henrique Costa', status: 'presente' },
      { alunoId: '2', alunoNome: 'Juliana Fernandes', status: 'presente' },
      { alunoId: '3', alunoNome: 'Lucas Almeida', status: 'presente' },
      { alunoId: '4', alunoNome: 'Mariana Santos', status: 'presente' },
      { alunoId: '5', alunoNome: 'Rafael Oliveira', status: 'presente' },
      { alunoId: '6', alunoNome: 'Camila Rodrigues', status: 'presente' },
      { alunoId: '7', alunoNome: 'Thiago Souza', status: 'presente' },
      { alunoId: '8', alunoNome: 'Amanda Silva', status: 'presente' },
      { alunoId: '9', alunoNome: 'Bruno Costa', status: 'ausente' },
      { alunoId: '10', alunoNome: 'Letícia Martins', status: 'presente' },
      { alunoId: '11', alunoNome: 'Gabriel Santos', status: 'presente' },
      { alunoId: '12', alunoNome: 'Patrícia Lima', status: 'presente' },
      { alunoId: '13', alunoNome: 'Fernando Rocha', status: 'presente' },
      { alunoId: '14', alunoNome: 'Carolina Mendes', status: 'presente' },
      { alunoId: '15', alunoNome: 'Diego Alves', status: 'presente' },
    ],
    dataCriacao: '2024-03-18',
  },
];

// Anotações de Alunos Mock - Anotações do instrutor João Santos
export const mockAnotacoes: AnotacaoAluno[] = [
  {
    id: 'an-1',
    alunoId: '1',
    alunoNome: 'Pedro Henrique Costa',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'desempenho',
    titulo: 'Excelente participação nas aulas',
    conteudo: 'Pedro tem demonstrado excelente compreensão dos conceitos de desenvolvimento web. Sempre faz perguntas relevantes e ajuda os colegas com dificuldades. Possui grande potencial para se tornar um desenvolvedor sênior.',
    privada: false,
    data: '2024-03-10',
    dataCriacao: '2024-03-10',
  },
  {
    id: 'an-2',
    alunoId: '4',
    alunoNome: 'Mariana Santos',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'desempenho',
    titulo: 'Destaque em CSS e Design',
    conteudo: 'Mariana tem um talento natural para design e estilização. Seus exercícios de CSS são sempre criativos e bem executados. Recomendo que explore mais a área de front-end e UX/UI.',
    privada: false,
    data: '2024-03-12',
    dataCriacao: '2024-03-12',
  },
  {
    id: 'an-3',
    alunoId: '5',
    alunoNome: 'Rafael Oliveira',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'desempenho',
    titulo: 'Evolução notável',
    conteudo: 'Rafael começou o curso com pouco conhecimento prévio, mas tem evoluído de forma impressionante. Seu empenho e dedicação são exemplares. Sempre entrega os exercícios no prazo e busca desafios extras.',
    privada: false,
    data: '2024-03-15',
    dataCriacao: '2024-03-15',
  },
  {
    id: 'an-4',
    alunoId: '9',
    alunoNome: 'Bruno Costa',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'alerta',
    titulo: 'Dificuldade de aprendizado - necessita acompanhamento',
    conteudo: 'Bruno tem demonstrado dificuldade em acompanhar o ritmo da turma, especialmente nos conceitos de JavaScript. Faltou à aula de avaliação. Precisa de acompanhamento individual urgente para não ficar muito defasado. Vou marcar um horário de reforço com ele.',
    privada: true,
    data: '2024-03-19',
    dataCriacao: '2024-03-19',
  },
  {
    id: 'an-5',
    alunoId: '3',
    alunoNome: 'Lucas Almeida',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'comportamento',
    titulo: 'Ausências impactando aprendizado',
    conteudo: 'Lucas faltou nas aulas 1 e 4, o que está impactando seu aprendizado. Quando presente, demonstra capacidade de acompanhar o conteúdo. Conversei com ele sobre a importância da presença contínua.',
    privada: false,
    data: '2024-03-14',
    dataCriacao: '2024-03-14',
  },
  {
    id: 'an-6',
    alunoId: '2',
    alunoNome: 'Juliana Fernandes',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'geral',
    titulo: 'Boa evolução e interesse',
    conteudo: 'Juliana tem demonstrado bastante interesse no curso e evolução constante. Suas perguntas são sempre pertinentes e demonstram que está estudando além do conteúdo das aulas.',
    privada: false,
    data: '2024-03-16',
    dataCriacao: '2024-03-16',
  },
  {
    id: 'an-7',
    alunoId: '14',
    alunoNome: 'Carolina Mendes',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'comportamento',
    titulo: 'Falta não justificada',
    conteudo: 'Carolina faltou à aula 3 sem justificativa. Quando presente, participa bem das atividades. Preciso verificar se está tudo bem com ela.',
    privada: true,
    data: '2024-03-12',
    dataCriacao: '2024-03-12',
  },
  {
    id: 'an-8',
    alunoId: '11',
    alunoNome: 'Gabriel Santos',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'desempenho',
    titulo: 'Bom desempenho em lógica de programação',
    conteudo: 'Gabriel tem se destacado nos exercícios de JavaScript. Demonstra facilidade com lógica de programação e resolução de problemas. Tem potencial para se especializar em back-end.',
    privada: false,
    data: '2024-03-17',
    dataCriacao: '2024-03-17',
  },
  {
    id: 'an-9',
    alunoId: '7',
    alunoNome: 'Thiago Souza',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'geral',
    titulo: 'Participação ativa e colaborativa',
    conteudo: 'Thiago sempre participa ativamente das discussões e ajuda os colegas. Tem demonstrado espírito de equipe e comprometimento com o aprendizado coletivo.',
    privada: false,
    data: '2024-03-18',
    dataCriacao: '2024-03-18',
  },
  {
    id: 'an-10',
    alunoId: '10',
    alunoNome: 'Letícia Martins',
    instrutorId: '3',
    instrutorNome: 'João Santos',
    turmaId: '1',
    tipo: 'desempenho',
    titulo: 'Progresso consistente',
    conteudo: 'Letícia mantém um ritmo de aprendizado muito consistente. Não é a mais rápida da turma, mas absorve bem todo o conteúdo e raramente comete os mesmos erros duas vezes.',
    privada: false,
    data: '2024-03-19',
    dataCriacao: '2024-03-19',
  },
];

// Métricas Gerais Mock
export const mockMetricasGerais: MetricasGerais = {
  totalTurmas: 8,
  turmasAtivas: 4,
  totalAlunos: 156,
  alunosAtivos: 142,
  totalInstrutores: 6,
  instrutoresAtivos: 5,
  totalInteressados: 45,
  interessadosNovos: 12,
  taxaConversao: 68.5,
  taxaEvasao: 8.9,
};

// Métricas Qualitativas Mock
export const mockMetricasQualitativas: import('./types').MetricaQualitativa[] = [
  {
    id: 'mq-1',
    alunoId: '1',
    alunoNome: 'Pedro Henrique Costa',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-15',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 4,
    habilidadeProgramacao: 4,
    candidatandoVagas: true,
    tipoOportunidade: 'processo_seletivo',
    interesseCursoTecnico: true,
    interesseGraduacao: true,
    areaInteresse: 'Análise e Desenvolvimento de Sistemas',
  },
  {
    id: 'mq-2',
    alunoId: '2',
    alunoNome: 'Juliana Fernandes',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-15',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 5,
    habilidadeProgramacao: 4,
    candidatandoVagas: true,
    tipoOportunidade: 'freelancer',
    interesseCursoTecnico: false,
    interesseGraduacao: true,
    areaInteresse: 'Engenharia de Software',
  },
  {
    id: 'mq-3',
    alunoId: '3',
    alunoNome: 'Lucas Almeida',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-16',
    satisfacaoCurso: 4,
    segurancaFerramentasDigitais: 3,
    habilidadeProgramacao: 3,
    candidatandoVagas: false,
    tipoOportunidade: 'nenhuma',
    interesseCursoTecnico: true,
    interesseGraduacao: false,
    areaInteresse: 'Técnico em Informática',
  },
  {
    id: 'mq-4',
    alunoId: '4',
    alunoNome: 'Mariana Santos',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-16',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 4,
    habilidadeProgramacao: 5,
    candidatandoVagas: true,
    tipoOportunidade: 'emprego',
    interesseCursoTecnico: true,
    interesseGraduacao: true,
    areaInteresse: 'Ciência da Computação',
  },
  {
    id: 'mq-5',
    alunoId: '5',
    alunoNome: 'Rafael Oliveira',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    dataResposta: '2024-10-17',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 5,
    habilidadeProgramacao: 5,
    candidatandoVagas: true,
    tipoOportunidade: 'emprego',
    interesseCursoTecnico: false,
    interesseGraduacao: true,
    areaInteresse: 'Sistemas de Informação',
  },
  {
    id: 'mq-6',
    alunoId: '6',
    alunoNome: 'Camila Rodrigues',
    turmaId: '2',
    turmaCodigo: 'WEB-2024-02',
    dataResposta: '2024-10-20',
    satisfacaoCurso: 4,
    segurancaFerramentasDigitais: 4,
    habilidadeProgramacao: 3,
    candidatandoVagas: true,
    tipoOportunidade: 'processo_seletivo',
    interesseCursoTecnico: true,
    interesseGraduacao: false,
  },
  {
    id: 'mq-7',
    alunoId: '7',
    alunoNome: 'Thiago Souza',
    turmaId: '2',
    turmaCodigo: 'WEB-2024-02',
    dataResposta: '2024-10-20',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 4,
    habilidadeProgramacao: 4,
    candidatandoVagas: true,
    tipoOportunidade: 'freelancer',
    interesseCursoTecnico: false,
    interesseGraduacao: true,
    areaInteresse: 'Desenvolvimento de Sistemas',
  },
  {
    id: 'mq-8',
    alunoId: '8',
    alunoNome: 'Amanda Silva',
    turmaId: '3',
    turmaCodigo: 'UX-2024-01',
    dataResposta: '2024-10-22',
    satisfacaoCurso: 5,
    segurancaFerramentasDigitais: 5,
    habilidadeProgramacao: 3,
    candidatandoVagas: true,
    tipoOportunidade: 'emprego',
    interesseCursoTecnico: true,
    interesseGraduacao: true,
    areaInteresse: 'Design Digital',
  },
];

// Histórias de Alunos Mock
export const mockHistoriasAlunos: import('./types').HistoriaAluno[] = [
  {
    id: 'hist-1',
    alunoId: '5',
    alunoNome: 'Rafael Oliveira',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    titulo: 'De Entregador a Desenvolvedor: Minha Jornada de Transformação',
    historia: 'Quando comecei o curso, eu trabalhava como entregador de aplicativo e nunca tinha pensado que programação poderia ser para mim. No início, tudo parecia muito difícil e eu quase desisti várias vezes. Mas os instrutores sempre acreditaram em mim e me incentivaram a continuar.\n\nDepois de 3 meses de curso, consegui meu primeiro freelance criando um site para um pequeno comércio do meu bairro. Foi incrível ver algo que EU criei funcionando e ajudando outra pessoa. Isso me motivou ainda mais.\n\nHoje, após concluir o curso, recebi uma proposta para trabalhar como desenvolvedor júnior em uma startup. Minha vida mudou completamente! Agora posso dar uma vida melhor para minha família e tenho um futuro que antes eu nem imaginava ser possível. Esse curso literalmente transformou minha vida.',
    categoria: 'transformacao',
    dataCompartilhamento: '2024-10-28',
    destacada: true,
    aprovada: true,
  },
  {
    id: 'hist-2',
    alunoId: '2',
    alunoNome: 'Juliana Fernandes',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    titulo: 'Primeira Freelancer e Muitos Sonhos pela Frente',
    historia: 'Sou mãe solo de duas crianças e sempre quis trabalhar de casa para estar mais presente na vida delas. Quando descobri o curso de programação, vi uma oportunidade de mudar minha realidade.\n\nO curso foi desafiador, especialmente conciliando com o cuidado das crianças, mas valeu cada esforço. Aprendi não só a programar, mas também a acreditar mais em mim mesma.\n\nAgora estou fazendo trabalhos como freelancer, criando sites e sistemas para pequenos negócios. Consigo trabalhar de casa, definir meus horários e estar presente quando minhas filhas precisam. Além disso, minha renda aumentou significativamente. Sou muito grata por essa oportunidade!',
    categoria: 'superacao',
    dataCompartilhamento: '2024-10-25',
    destacada: true,
    aprovada: true,
  },
  {
    id: 'hist-3',
    alunoId: '4',
    alunoNome: 'Mariana Santos',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    titulo: 'Conquistando Meu Primeiro Emprego na Área de TI',
    historia: 'Sempre tive curiosidade por tecnologia, mas nunca tinha tido a oportunidade de estudar formalmente. Quando me inscrevi no curso, estava desempregada e muito insegura.\n\nDurante o curso, descobri que tinha talento para programação! Os projetos que desenvolvi me deram confiança para me candidatar a vagas. Após enviar meu portfólio para várias empresas, recebi três convites para entrevistas.\n\nHoje estou feliz trabalhando como desenvolvedora júnior em uma empresa de tecnologia. Além do salário justo, tenho plano de saúde e outros benefícios que nunca tinha tido antes. Estou construindo uma carreira sólida e tenho planos de me especializar ainda mais!',
    categoria: 'conquista',
    dataCompartilhamento: '2024-10-26',
    destacada: true,
    aprovada: true,
  },
  {
    id: 'hist-4',
    alunoId: '1',
    alunoNome: 'Pedro Henrique Costa',
    turmaId: '1',
    turmaCodigo: 'WEB-2024-01',
    titulo: 'Programação Abriu Portas que Eu Nem Sabia que Existiam',
    historia: 'Eu estava preso em um emprego que não me satisfazia e não via perspectiva de crescimento. Decidi me inscrever no curso de programação por indicação de um amigo, mas confesso que estava cético.\n\nDurante o curso, percebi que programação é muito mais do que escrever código - é resolver problemas, criar soluções e ajudar pessoas. Isso mudou completamente minha visão.\n\nEstou em processo seletivo para três empresas diferentes e já recebi uma proposta. Mais do que isso, descobri uma paixão que não sabia que tinha. Agora acordo animado para estudar e criar projetos. É incrível sentir que finalmente encontrei meu caminho!',
    categoria: 'inspiracao',
    dataCompartilhamento: '2024-10-27',
    destacada: false,
    aprovada: true,
  },
  {
    id: 'hist-5',
    alunoId: '8',
    alunoNome: 'Amanda Silva',
    turmaId: '3',
    turmaCodigo: 'UX-2024-01',
    titulo: 'Do Sonho à Realidade: Minha Carreira em UX Design',
    historia: 'Sempre gostei de desenhar e criar coisas, mas nunca pensei que isso poderia se tornar uma profissão. O curso de UX/UI Design me mostrou que posso unir criatividade com tecnologia.\n\nAprendi a criar interfaces que realmente ajudam as pessoas e isso me realiza profissionalmente. Durante o curso, redesenhei o aplicativo de uma ONG local como projeto final, e isso abriu muitas portas.\n\nRecentemente, comecei a trabalhar em uma agência digital como designer júnior. Ver meus designs saindo do papel e sendo usados por milhares de pessoas é uma sensação indescritível. Agradeço imensamente pela oportunidade que esse curso me deu!',
    categoria: 'conquista',
    dataCompartilhamento: '2024-10-29',
    destacada: false,
    aprovada: true,
  },
  {
    id: 'hist-6',
    alunoId: '7',
    alunoNome: 'Thiago Souza',
    turmaId: '2',
    turmaCodigo: 'WEB-2024-02',
    titulo: 'Superando Desafios e Alcançando Objetivos',
    historia: 'Venho de uma família humilde e sempre precisei trabalhar desde cedo para ajudar em casa. Estudar programação era um sonho que parecia distante demais.\n\nQuando consegui a vaga no curso gratuito, vi uma luz no fim do túnel. Foi difícil conciliar trabalho e estudos, mas cada linha de código que funcionava era uma vitória.\n\nHoje estou fazendo pequenos trabalhos como freelancer e juntando experiência. Meu objetivo é conseguir um emprego fixo na área até o final do ano. Sei que vou conseguir, porque se cheguei até aqui, posso ir ainda mais longe!',
    categoria: 'superacao',
    dataCompartilhamento: '2024-10-30',
    destacada: false,
    aprovada: true,
  },
];
